[build]
  bin = "./tmp/erg-server.exe"
  cmd = "make swag; if ($LASTEXITCODE -eq 0) { go build -o ./tmp/erg-server.exe ./cmd/server }"
  delay = 1000
  exclude_dir = ["tmp", "vendor", ".git", "migrations", "docs"]
[misc]
  close_on_error = true
  clean_on_exit = true
