// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/lib/trending/v1/trending.proto

package trendingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrendingService_GetTopTopics_FullMethodName      = "/erg.ninja.lib.trending.v1.TrendingService/GetTopTopics"
	TrendingService_GetTopic_FullMethodName          = "/erg.ninja.lib.trending.v1.TrendingService/GetTopic"
	TrendingService_SearchTopics_FullMethodName      = "/erg.ninja.lib.trending.v1.TrendingService/SearchTopics"
	TrendingService_GetTopicNews_FullMethodName      = "/erg.ninja.lib.trending.v1.TrendingService/GetTopicNews"
	TrendingService_GetSnapshot_FullMethodName       = "/erg.ninja.lib.trending.v1.TrendingService/GetSnapshot"
	TrendingService_GetLatestSnapshot_FullMethodName = "/erg.ninja.lib.trending.v1.TrendingService/GetLatestSnapshot"
	TrendingService_Refresh_FullMethodName           = "/erg.ninja.lib.trending.v1.TrendingService/Refresh"
	TrendingService_GetKeywordTrend_FullMethodName   = "/erg.ninja.lib.trending.v1.TrendingService/GetKeywordTrend"
	TrendingService_GetStats_FullMethodName          = "/erg.ninja.lib.trending.v1.TrendingService/GetStats"
)

// TrendingServiceClient is the client API for TrendingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrendingServiceClient interface {
	// Get top trending topics
	GetTopTopics(ctx context.Context, in *GetTopTopicsRequest, opts ...grpc.CallOption) (*GetTopTopicsResponse, error)
	// Get a single topic by name or slug
	GetTopic(ctx context.Context, in *GetTopicRequest, opts ...grpc.CallOption) (*GetTopicResponse, error)
	// Search topics by keyword
	SearchTopics(ctx context.Context, in *SearchTopicsRequest, opts ...grpc.CallOption) (*SearchTopicsResponse, error)
	// Get news articles for a specific topic
	GetTopicNews(ctx context.Context, in *GetTopicNewsRequest, opts ...grpc.CallOption) (*GetTopicNewsResponse, error)
	// Point-in-time snapshots
	GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*GetSnapshotResponse, error)
	GetLatestSnapshot(ctx context.Context, in *GetLatestSnapshotRequest, opts ...grpc.CallOption) (*GetLatestSnapshotResponse, error)
	// Trigger refresh (typically runs as scheduled job)
	Refresh(ctx context.Context, in *RefreshTrendingRequest, opts ...grpc.CallOption) (*RefreshTrendingResponse, error)
	// Volume timeline for a specific keyword
	GetKeywordTrend(ctx context.Context, in *GetKeywordTrendRequest, opts ...grpc.CallOption) (*GetKeywordTrendResponse, error)
	// Aggregate statistics
	GetStats(ctx context.Context, in *GetTrendingStatsRequest, opts ...grpc.CallOption) (*GetTrendingStatsResponse, error)
}

type trendingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrendingServiceClient(cc grpc.ClientConnInterface) TrendingServiceClient {
	return &trendingServiceClient{cc}
}

func (c *trendingServiceClient) GetTopTopics(ctx context.Context, in *GetTopTopicsRequest, opts ...grpc.CallOption) (*GetTopTopicsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopTopicsResponse)
	err := c.cc.Invoke(ctx, TrendingService_GetTopTopics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trendingServiceClient) GetTopic(ctx context.Context, in *GetTopicRequest, opts ...grpc.CallOption) (*GetTopicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopicResponse)
	err := c.cc.Invoke(ctx, TrendingService_GetTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trendingServiceClient) SearchTopics(ctx context.Context, in *SearchTopicsRequest, opts ...grpc.CallOption) (*SearchTopicsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchTopicsResponse)
	err := c.cc.Invoke(ctx, TrendingService_SearchTopics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trendingServiceClient) GetTopicNews(ctx context.Context, in *GetTopicNewsRequest, opts ...grpc.CallOption) (*GetTopicNewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopicNewsResponse)
	err := c.cc.Invoke(ctx, TrendingService_GetTopicNews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trendingServiceClient) GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*GetSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSnapshotResponse)
	err := c.cc.Invoke(ctx, TrendingService_GetSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trendingServiceClient) GetLatestSnapshot(ctx context.Context, in *GetLatestSnapshotRequest, opts ...grpc.CallOption) (*GetLatestSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLatestSnapshotResponse)
	err := c.cc.Invoke(ctx, TrendingService_GetLatestSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trendingServiceClient) Refresh(ctx context.Context, in *RefreshTrendingRequest, opts ...grpc.CallOption) (*RefreshTrendingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshTrendingResponse)
	err := c.cc.Invoke(ctx, TrendingService_Refresh_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trendingServiceClient) GetKeywordTrend(ctx context.Context, in *GetKeywordTrendRequest, opts ...grpc.CallOption) (*GetKeywordTrendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKeywordTrendResponse)
	err := c.cc.Invoke(ctx, TrendingService_GetKeywordTrend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trendingServiceClient) GetStats(ctx context.Context, in *GetTrendingStatsRequest, opts ...grpc.CallOption) (*GetTrendingStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrendingStatsResponse)
	err := c.cc.Invoke(ctx, TrendingService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrendingServiceServer is the server API for TrendingService service.
// All implementations must embed UnimplementedTrendingServiceServer
// for forward compatibility.
type TrendingServiceServer interface {
	// Get top trending topics
	GetTopTopics(context.Context, *GetTopTopicsRequest) (*GetTopTopicsResponse, error)
	// Get a single topic by name or slug
	GetTopic(context.Context, *GetTopicRequest) (*GetTopicResponse, error)
	// Search topics by keyword
	SearchTopics(context.Context, *SearchTopicsRequest) (*SearchTopicsResponse, error)
	// Get news articles for a specific topic
	GetTopicNews(context.Context, *GetTopicNewsRequest) (*GetTopicNewsResponse, error)
	// Point-in-time snapshots
	GetSnapshot(context.Context, *GetSnapshotRequest) (*GetSnapshotResponse, error)
	GetLatestSnapshot(context.Context, *GetLatestSnapshotRequest) (*GetLatestSnapshotResponse, error)
	// Trigger refresh (typically runs as scheduled job)
	Refresh(context.Context, *RefreshTrendingRequest) (*RefreshTrendingResponse, error)
	// Volume timeline for a specific keyword
	GetKeywordTrend(context.Context, *GetKeywordTrendRequest) (*GetKeywordTrendResponse, error)
	// Aggregate statistics
	GetStats(context.Context, *GetTrendingStatsRequest) (*GetTrendingStatsResponse, error)
	mustEmbedUnimplementedTrendingServiceServer()
}

// UnimplementedTrendingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrendingServiceServer struct{}

func (UnimplementedTrendingServiceServer) GetTopTopics(context.Context, *GetTopTopicsRequest) (*GetTopTopicsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopTopics not implemented")
}
func (UnimplementedTrendingServiceServer) GetTopic(context.Context, *GetTopicRequest) (*GetTopicResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopic not implemented")
}
func (UnimplementedTrendingServiceServer) SearchTopics(context.Context, *SearchTopicsRequest) (*SearchTopicsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchTopics not implemented")
}
func (UnimplementedTrendingServiceServer) GetTopicNews(context.Context, *GetTopicNewsRequest) (*GetTopicNewsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopicNews not implemented")
}
func (UnimplementedTrendingServiceServer) GetSnapshot(context.Context, *GetSnapshotRequest) (*GetSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSnapshot not implemented")
}
func (UnimplementedTrendingServiceServer) GetLatestSnapshot(context.Context, *GetLatestSnapshotRequest) (*GetLatestSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatestSnapshot not implemented")
}
func (UnimplementedTrendingServiceServer) Refresh(context.Context, *RefreshTrendingRequest) (*RefreshTrendingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Refresh not implemented")
}
func (UnimplementedTrendingServiceServer) GetKeywordTrend(context.Context, *GetKeywordTrendRequest) (*GetKeywordTrendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKeywordTrend not implemented")
}
func (UnimplementedTrendingServiceServer) GetStats(context.Context, *GetTrendingStatsRequest) (*GetTrendingStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedTrendingServiceServer) mustEmbedUnimplementedTrendingServiceServer() {}
func (UnimplementedTrendingServiceServer) testEmbeddedByValue()                         {}

// UnsafeTrendingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrendingServiceServer will
// result in compilation errors.
type UnsafeTrendingServiceServer interface {
	mustEmbedUnimplementedTrendingServiceServer()
}

func RegisterTrendingServiceServer(s grpc.ServiceRegistrar, srv TrendingServiceServer) {
	// If the following call panics, it indicates UnimplementedTrendingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrendingService_ServiceDesc, srv)
}

func _TrendingService_GetTopTopics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopTopicsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendingServiceServer).GetTopTopics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrendingService_GetTopTopics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendingServiceServer).GetTopTopics(ctx, req.(*GetTopTopicsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrendingService_GetTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendingServiceServer).GetTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrendingService_GetTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendingServiceServer).GetTopic(ctx, req.(*GetTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrendingService_SearchTopics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchTopicsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendingServiceServer).SearchTopics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrendingService_SearchTopics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendingServiceServer).SearchTopics(ctx, req.(*SearchTopicsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrendingService_GetTopicNews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopicNewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendingServiceServer).GetTopicNews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrendingService_GetTopicNews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendingServiceServer).GetTopicNews(ctx, req.(*GetTopicNewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrendingService_GetSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendingServiceServer).GetSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrendingService_GetSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendingServiceServer).GetSnapshot(ctx, req.(*GetSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrendingService_GetLatestSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendingServiceServer).GetLatestSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrendingService_GetLatestSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendingServiceServer).GetLatestSnapshot(ctx, req.(*GetLatestSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrendingService_Refresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTrendingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendingServiceServer).Refresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrendingService_Refresh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendingServiceServer).Refresh(ctx, req.(*RefreshTrendingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrendingService_GetKeywordTrend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeywordTrendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendingServiceServer).GetKeywordTrend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrendingService_GetKeywordTrend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendingServiceServer).GetKeywordTrend(ctx, req.(*GetKeywordTrendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrendingService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrendingStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendingServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrendingService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendingServiceServer).GetStats(ctx, req.(*GetTrendingStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrendingService_ServiceDesc is the grpc.ServiceDesc for TrendingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrendingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "erg.ninja.lib.trending.v1.TrendingService",
	HandlerType: (*TrendingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTopTopics",
			Handler:    _TrendingService_GetTopTopics_Handler,
		},
		{
			MethodName: "GetTopic",
			Handler:    _TrendingService_GetTopic_Handler,
		},
		{
			MethodName: "SearchTopics",
			Handler:    _TrendingService_SearchTopics_Handler,
		},
		{
			MethodName: "GetTopicNews",
			Handler:    _TrendingService_GetTopicNews_Handler,
		},
		{
			MethodName: "GetSnapshot",
			Handler:    _TrendingService_GetSnapshot_Handler,
		},
		{
			MethodName: "GetLatestSnapshot",
			Handler:    _TrendingService_GetLatestSnapshot_Handler,
		},
		{
			MethodName: "Refresh",
			Handler:    _TrendingService_Refresh_Handler,
		},
		{
			MethodName: "GetKeywordTrend",
			Handler:    _TrendingService_GetKeywordTrend_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _TrendingService_GetStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/lib/trending/v1/trending.proto",
}
