// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/lib/trending/v1/trending.proto

package trendingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrendingSource int32

const (
	TrendingSource_TRENDING_SOURCE_UNSPECIFIED TrendingSource = 0
	TrendingSource_TRENDING_SOURCE_GOOGLE      TrendingSource = 1
	TrendingSource_TRENDING_SOURCE_NEWS_API    TrendingSource = 2
	TrendingSource_TRENDING_SOURCE_REDDIT      TrendingSource = 3
	TrendingSource_TRENDING_SOURCE_TWITTER     TrendingSource = 4
	TrendingSource_TRENDING_SOURCE_INTERNAL    TrendingSource = 5
)

// Enum value maps for TrendingSource.
var (
	TrendingSource_name = map[int32]string{
		0: "TRENDING_SOURCE_UNSPECIFIED",
		1: "TRENDING_SOURCE_GOOGLE",
		2: "TRENDING_SOURCE_NEWS_API",
		3: "TRENDING_SOURCE_REDDIT",
		4: "TRENDING_SOURCE_TWITTER",
		5: "TRENDING_SOURCE_INTERNAL",
	}
	TrendingSource_value = map[string]int32{
		"TRENDING_SOURCE_UNSPECIFIED": 0,
		"TRENDING_SOURCE_GOOGLE":      1,
		"TRENDING_SOURCE_NEWS_API":    2,
		"TRENDING_SOURCE_REDDIT":      3,
		"TRENDING_SOURCE_TWITTER":     4,
		"TRENDING_SOURCE_INTERNAL":    5,
	}
)

func (x TrendingSource) Enum() *TrendingSource {
	p := new(TrendingSource)
	*p = x
	return p
}

func (x TrendingSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrendingSource) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_lib_trending_v1_trending_proto_enumTypes[0].Descriptor()
}

func (TrendingSource) Type() protoreflect.EnumType {
	return &file_proto_lib_trending_v1_trending_proto_enumTypes[0]
}

func (x TrendingSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrendingSource.Descriptor instead.
func (TrendingSource) EnumDescriptor() ([]byte, []int) {
	return file_proto_lib_trending_v1_trending_proto_rawDescGZIP(), []int{0}
}

type TimeRange int32

const (
	TimeRange_TIME_RANGE_UNSPECIFIED TimeRange = 0
	TimeRange_TIME_RANGE_HOURLY      TimeRange = 1
	TimeRange_TIME_RANGE_DAILY       TimeRange = 2
	TimeRange_TIME_RANGE_WEEKLY      TimeRange = 3
	TimeRange_TIME_RANGE_MONTHLY     TimeRange = 4
)

// Enum value maps for TimeRange.
var (
	TimeRange_name = map[int32]string{
		0: "TIME_RANGE_UNSPECIFIED",
		1: "TIME_RANGE_HOURLY",
		2: "TIME_RANGE_DAILY",
		3: "TIME_RANGE_WEEKLY",
		4: "TIME_RANGE_MONTHLY",
	}
	TimeRange_value = map[string]int32{
		"TIME_RANGE_UNSPECIFIED": 0,
		"TIME_RANGE_HOURLY":      1,
		"TIME_RANGE_DAILY":       2,
		"TIME_RANGE_WEEKLY":      3,
		"TIME_RANGE_MONTHLY":     4,
	}
)

func (x TimeRange) Enum() *TimeRange {
	p := new(TimeRange)
	*p = x
	return p
}

func (x TimeRange) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeRange) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_lib_trending_v1_trending_proto_enumTypes[1].Descriptor()
}

func (TimeRange) Type() protoreflect.EnumType {
	return &file_proto_lib_trending_v1_trending_proto_enumTypes[1]
}

func (x TimeRange) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeRange.Descriptor instead.
func (TimeRange) EnumDescriptor() ([]byte, []int) {
	return file_proto_lib_trending_v1_trending_proto_rawDescGZIP(), []int{1}
}

type TrendingTopic struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Topic           string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Slug            string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Score           float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`  // 0–100
	Volume          int32                  `protobuf:"varint,5,opt,name=volume,proto3" json:"volume,omitempty"` // estimated mention count
	Source          TrendingSource         `protobuf:"varint,6,opt,name=source,proto3,enum=erg.ninja.lib.trending.v1.TrendingSource" json:"source,omitempty"`
	Keywords        []string               `protobuf:"bytes,7,rep,name=keywords,proto3" json:"keywords,omitempty"`
	Urls            []string               `protobuf:"bytes,8,rep,name=urls,proto3" json:"urls,omitempty"`
	Timeline        []int32                `protobuf:"varint,9,rep,packed,name=timeline,proto3" json:"timeline,omitempty"` // relative volume per time bucket
	LastRefreshedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_refreshed_at,json=lastRefreshedAt,proto3" json:"last_refreshed_at,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TrendingTopic) Reset() {
	*x = TrendingTopic{}
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendingTopic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendingTopic) ProtoMessage() {}

func (x *TrendingTopic) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendingTopic.ProtoReflect.Descriptor instead.
func (*TrendingTopic) Descriptor() ([]byte, []int) {
	return file_proto_lib_trending_v1_trending_proto_rawDescGZIP(), []int{0}
}

func (x *TrendingTopic) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TrendingTopic) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *TrendingTopic) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *TrendingTopic) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *TrendingTopic) GetVolume() int32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *TrendingTopic) GetSource() TrendingSource {
	if x != nil {
		return x.Source
	}
	return TrendingSource_TRENDING_SOURCE_UNSPECIFIED
}

func (x *TrendingTopic) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *TrendingTopic) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *TrendingTopic) GetTimeline() []int32 {
	if x != nil {
		return x.Timeline
	}
	return nil
}

func (x *TrendingTopic) GetLastRefreshedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRefreshedAt
	}
	return nil
}

func (x *TrendingTopic) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TrendingTopic) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetTopTopicsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                                                                   // default 10, max 100
	TimeRange     TimeRange              `protobuf:"varint,3,opt,name=time_range,json=timeRange,proto3,enum=erg.ninja.lib.trending.v1.TimeRange" json:"time_range,omitempty"` // default TIME_RANGE_DAILY
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`                                                                  // optional filter
	Language      string                 `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`                                                              // optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopTopicsRequest) Reset() {
	*x = GetTopTopicsRequest{}
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopTopicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopTopicsRequest) ProtoMessage() {}

func (x *GetTopTopicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopTopicsRequest.ProtoReflect.Descriptor instead.
func (*GetTopTopicsRequest) Descriptor() ([]byte, []int) {
	return file_proto_lib_trending_v1_trending_proto_rawDescGZIP(), []int{1}
}

func (x *GetTopTopicsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetTopTopicsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTopTopicsRequest) GetTimeRange() TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return TimeRange_TIME_RANGE_UNSPECIFIED
}

func (x *GetTopTopicsRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GetTopTopicsRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type GetTopTopicsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []*TrendingTopic       `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	GeneratedAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	TimeRange     TimeRange              `protobuf:"varint,3,opt,name=time_range,json=timeRange,proto3,enum=erg.ninja.lib.trending.v1.TimeRange" json:"time_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopTopicsResponse) Reset() {
	*x = GetTopTopicsResponse{}
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopTopicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopTopicsResponse) ProtoMessage() {}

func (x *GetTopTopicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopTopicsResponse.ProtoReflect.Descriptor instead.
func (*GetTopTopicsResponse) Descriptor() ([]byte, []int) {
	return file_proto_lib_trending_v1_trending_proto_rawDescGZIP(), []int{2}
}

func (x *GetTopTopicsResponse) GetTopics() []*TrendingTopic {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *GetTopTopicsResponse) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

func (x *GetTopTopicsResponse) GetTimeRange() TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return TimeRange_TIME_RANGE_UNSPECIFIED
}

type GetTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"` // URL-encoded or exact match
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`   // optional: slug form
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopicRequest) Reset() {
	*x = GetTopicRequest{}
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopicRequest) ProtoMessage() {}

func (x *GetTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopicRequest.ProtoReflect.Descriptor instead.
func (*GetTopicRequest) Descriptor() ([]byte, []int) {
	return file_proto_lib_trending_v1_trending_proto_rawDescGZIP(), []int{3}
}

func (x *GetTopicRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetTopicRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *GetTopicRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type GetTopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         *TrendingTopic         `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopicResponse) Reset() {
	*x = GetTopicResponse{}
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopicResponse) ProtoMessage() {}

func (x *GetTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopicResponse.ProtoReflect.Descriptor instead.
func (*GetTopicResponse) Descriptor() ([]byte, []int) {
	return file_proto_lib_trending_v1_trending_proto_rawDescGZIP(), []int{4}
}

func (x *GetTopicResponse) GetTopic() *TrendingTopic {
	if x != nil {
		return x.Topic
	}
	return nil
}

type SearchTopicsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTopicsRequest) Reset() {
	*x = SearchTopicsRequest{}
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTopicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTopicsRequest) ProtoMessage() {}

func (x *SearchTopicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTopicsRequest.ProtoReflect.Descriptor instead.
func (*SearchTopicsRequest) Descriptor() ([]byte, []int) {
	return file_proto_lib_trending_v1_trending_proto_rawDescGZIP(), []int{5}
}

func (x *SearchTopicsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SearchTopicsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchTopicsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchTopicsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []*TrendingTopic       `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTopicsResponse) Reset() {
	*x = SearchTopicsResponse{}
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTopicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTopicsResponse) ProtoMessage() {}

func (x *SearchTopicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTopicsResponse.ProtoReflect.Descriptor instead.
func (*SearchTopicsResponse) Descriptor() ([]byte, []int) {
	return file_proto_lib_trending_v1_trending_proto_rawDescGZIP(), []int{6}
}

func (x *SearchTopicsResponse) GetTopics() []*TrendingTopic {
	if x != nil {
		return x.Topics
	}
	return nil
}

type NewsArticle struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Topic          string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Headline       string                 `protobuf:"bytes,3,opt,name=headline,proto3" json:"headline,omitempty"`
	Source         string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Url            string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	PublishedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	RelevanceScore float64                `protobuf:"fixed64,7,opt,name=relevance_score,json=relevanceScore,proto3" json:"relevance_score,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NewsArticle) Reset() {
	*x = NewsArticle{}
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewsArticle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewsArticle) ProtoMessage() {}

func (x *NewsArticle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewsArticle.ProtoReflect.Descriptor instead.
func (*NewsArticle) Descriptor() ([]byte, []int) {
	return file_proto_lib_trending_v1_trending_proto_rawDescGZIP(), []int{7}
}

func (x *NewsArticle) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NewsArticle) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *NewsArticle) GetHeadline() string {
	if x != nil {
		return x.Headline
	}
	return ""
}

func (x *NewsArticle) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *NewsArticle) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *NewsArticle) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *NewsArticle) GetRelevanceScore() float64 {
	if x != nil {
		return x.RelevanceScore
	}
	return 0
}

func (x *NewsArticle) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *NewsArticle) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetTopicNewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"` // default 10
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopicNewsRequest) Reset() {
	*x = GetTopicNewsRequest{}
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopicNewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopicNewsRequest) ProtoMessage() {}

func (x *GetTopicNewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopicNewsRequest.ProtoReflect.Descriptor instead.
func (*GetTopicNewsRequest) Descriptor() ([]byte, []int) {
	return file_proto_lib_trending_v1_trending_proto_rawDescGZIP(), []int{8}
}

func (x *GetTopicNewsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetTopicNewsRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *GetTopicNewsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTopicNewsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetTopicNewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Articles      []*NewsArticle         `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopicNewsResponse) Reset() {
	*x = GetTopicNewsResponse{}
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopicNewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopicNewsResponse) ProtoMessage() {}

func (x *GetTopicNewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopicNewsResponse.ProtoReflect.Descriptor instead.
func (*GetTopicNewsResponse) Descriptor() ([]byte, []int) {
	return file_proto_lib_trending_v1_trending_proto_rawDescGZIP(), []int{9}
}

func (x *GetTopicNewsResponse) GetArticles() []*NewsArticle {
	if x != nil {
		return x.Articles
	}
	return nil
}

type TrendingSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Topics        []*TrendingTopic       `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	TopicCount    int32                  `protobuf:"varint,3,opt,name=topic_count,json=topicCount,proto3" json:"topic_count,omitempty"`
	GeneratedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendingSnapshot) Reset() {
	*x = TrendingSnapshot{}
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendingSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendingSnapshot) ProtoMessage() {}

func (x *TrendingSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendingSnapshot.ProtoReflect.Descriptor instead.
func (*TrendingSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_lib_trending_v1_trending_proto_rawDescGZIP(), []int{10}
}

func (x *TrendingSnapshot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TrendingSnapshot) GetTopics() []*TrendingTopic {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *TrendingSnapshot) GetTopicCount() int32 {
	if x != nil {
		return x.TopicCount
	}
	return 0
}

func (x *TrendingSnapshot) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

func (x *TrendingSnapshot) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SnapshotId    string                 `protobuf:"bytes,2,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotRequest) Reset() {
	*x = GetSnapshotRequest{}
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotRequest) ProtoMessage() {}

func (x *GetSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_lib_trending_v1_trending_proto_rawDescGZIP(), []int{11}
}

func (x *GetSnapshotRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetSnapshotRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

type GetSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *TrendingSnapshot      `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotResponse) Reset() {
	*x = GetSnapshotResponse{}
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotResponse) ProtoMessage() {}

func (x *GetSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_proto_lib_trending_v1_trending_proto_rawDescGZIP(), []int{12}
}

func (x *GetSnapshotResponse) GetSnapshot() *TrendingSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type GetLatestSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	TimeRange     TimeRange              `protobuf:"varint,2,opt,name=time_range,json=timeRange,proto3,enum=erg.ninja.lib.trending.v1.TimeRange" json:"time_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestSnapshotRequest) Reset() {
	*x = GetLatestSnapshotRequest{}
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestSnapshotRequest) ProtoMessage() {}

func (x *GetLatestSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetLatestSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_lib_trending_v1_trending_proto_rawDescGZIP(), []int{13}
}

func (x *GetLatestSnapshotRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetLatestSnapshotRequest) GetTimeRange() TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return TimeRange_TIME_RANGE_UNSPECIFIED
}

type GetLatestSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *TrendingSnapshot      `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestSnapshotResponse) Reset() {
	*x = GetLatestSnapshotResponse{}
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestSnapshotResponse) ProtoMessage() {}

func (x *GetLatestSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetLatestSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_proto_lib_trending_v1_trending_proto_rawDescGZIP(), []int{14}
}

func (x *GetLatestSnapshotResponse) GetSnapshot() *TrendingSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type RefreshTrendingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Source        TrendingSource         `protobuf:"varint,2,opt,name=source,proto3,enum=erg.ninja.lib.trending.v1.TrendingSource" json:"source,omitempty"` // which source to refresh, 0 = all
	Force         bool                   `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`                                                 // bypass cache
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTrendingRequest) Reset() {
	*x = RefreshTrendingRequest{}
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTrendingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTrendingRequest) ProtoMessage() {}

func (x *RefreshTrendingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTrendingRequest.ProtoReflect.Descriptor instead.
func (*RefreshTrendingRequest) Descriptor() ([]byte, []int) {
	return file_proto_lib_trending_v1_trending_proto_rawDescGZIP(), []int{15}
}

func (x *RefreshTrendingRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RefreshTrendingRequest) GetSource() TrendingSource {
	if x != nil {
		return x.Source
	}
	return TrendingSource_TRENDING_SOURCE_UNSPECIFIED
}

func (x *RefreshTrendingRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type RefreshTrendingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "ok","error","partial"
	TopicCount    int32                  `protobuf:"varint,2,opt,name=topic_count,json=topicCount,proto3" json:"topic_count,omitempty"`
	NewsCount     int32                  `protobuf:"varint,3,opt,name=news_count,json=newsCount,proto3" json:"news_count,omitempty"`
	GeneratedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTrendingResponse) Reset() {
	*x = RefreshTrendingResponse{}
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTrendingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTrendingResponse) ProtoMessage() {}

func (x *RefreshTrendingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTrendingResponse.ProtoReflect.Descriptor instead.
func (*RefreshTrendingResponse) Descriptor() ([]byte, []int) {
	return file_proto_lib_trending_v1_trending_proto_rawDescGZIP(), []int{16}
}

func (x *RefreshTrendingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RefreshTrendingResponse) GetTopicCount() int32 {
	if x != nil {
		return x.TopicCount
	}
	return 0
}

func (x *RefreshTrendingResponse) GetNewsCount() int32 {
	if x != nil {
		return x.NewsCount
	}
	return 0
}

func (x *RefreshTrendingResponse) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

func (x *RefreshTrendingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetKeywordTrendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Keyword       string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	TimeRange     TimeRange              `protobuf:"varint,3,opt,name=time_range,json=timeRange,proto3,enum=erg.ninja.lib.trending.v1.TimeRange" json:"time_range,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeywordTrendRequest) Reset() {
	*x = GetKeywordTrendRequest{}
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeywordTrendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeywordTrendRequest) ProtoMessage() {}

func (x *GetKeywordTrendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeywordTrendRequest.ProtoReflect.Descriptor instead.
func (*GetKeywordTrendRequest) Descriptor() ([]byte, []int) {
	return file_proto_lib_trending_v1_trending_proto_rawDescGZIP(), []int{17}
}

func (x *GetKeywordTrendRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetKeywordTrendRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *GetKeywordTrendRequest) GetTimeRange() TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return TimeRange_TIME_RANGE_UNSPECIFIED
}

func (x *GetKeywordTrendRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type KeywordTrendPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Volume        int32                  `protobuf:"varint,2,opt,name=volume,proto3" json:"volume,omitempty"`
	Score         float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeywordTrendPoint) Reset() {
	*x = KeywordTrendPoint{}
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeywordTrendPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeywordTrendPoint) ProtoMessage() {}

func (x *KeywordTrendPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeywordTrendPoint.ProtoReflect.Descriptor instead.
func (*KeywordTrendPoint) Descriptor() ([]byte, []int) {
	return file_proto_lib_trending_v1_trending_proto_rawDescGZIP(), []int{18}
}

func (x *KeywordTrendPoint) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *KeywordTrendPoint) GetVolume() int32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *KeywordTrendPoint) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type GetKeywordTrendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	TimeRange     TimeRange              `protobuf:"varint,2,opt,name=time_range,json=timeRange,proto3,enum=erg.ninja.lib.trending.v1.TimeRange" json:"time_range,omitempty"`
	Points        []*KeywordTrendPoint   `protobuf:"bytes,3,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeywordTrendResponse) Reset() {
	*x = GetKeywordTrendResponse{}
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeywordTrendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeywordTrendResponse) ProtoMessage() {}

func (x *GetKeywordTrendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeywordTrendResponse.ProtoReflect.Descriptor instead.
func (*GetKeywordTrendResponse) Descriptor() ([]byte, []int) {
	return file_proto_lib_trending_v1_trending_proto_rawDescGZIP(), []int{19}
}

func (x *GetKeywordTrendResponse) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *GetKeywordTrendResponse) GetTimeRange() TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return TimeRange_TIME_RANGE_UNSPECIFIED
}

func (x *GetKeywordTrendResponse) GetPoints() []*KeywordTrendPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type GetTrendingStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrendingStatsRequest) Reset() {
	*x = GetTrendingStatsRequest{}
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrendingStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrendingStatsRequest) ProtoMessage() {}

func (x *GetTrendingStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrendingStatsRequest.ProtoReflect.Descriptor instead.
func (*GetTrendingStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_lib_trending_v1_trending_proto_rawDescGZIP(), []int{20}
}

func (x *GetTrendingStatsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type TrendingStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalTopics     int32                  `protobuf:"varint,1,opt,name=total_topics,json=totalTopics,proto3" json:"total_topics,omitempty"`
	ActiveSources   int32                  `protobuf:"varint,2,opt,name=active_sources,json=activeSources,proto3" json:"active_sources,omitempty"`
	LastRefreshAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_refresh_at,json=lastRefreshAt,proto3" json:"last_refresh_at,omitempty"`
	NewsArticles    int32                  `protobuf:"varint,4,opt,name=news_articles,json=newsArticles,proto3" json:"news_articles,omitempty"`
	SnapshotsStored int32                  `protobuf:"varint,5,opt,name=snapshots_stored,json=snapshotsStored,proto3" json:"snapshots_stored,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TrendingStats) Reset() {
	*x = TrendingStats{}
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendingStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendingStats) ProtoMessage() {}

func (x *TrendingStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendingStats.ProtoReflect.Descriptor instead.
func (*TrendingStats) Descriptor() ([]byte, []int) {
	return file_proto_lib_trending_v1_trending_proto_rawDescGZIP(), []int{21}
}

func (x *TrendingStats) GetTotalTopics() int32 {
	if x != nil {
		return x.TotalTopics
	}
	return 0
}

func (x *TrendingStats) GetActiveSources() int32 {
	if x != nil {
		return x.ActiveSources
	}
	return 0
}

func (x *TrendingStats) GetLastRefreshAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRefreshAt
	}
	return nil
}

func (x *TrendingStats) GetNewsArticles() int32 {
	if x != nil {
		return x.NewsArticles
	}
	return 0
}

func (x *TrendingStats) GetSnapshotsStored() int32 {
	if x != nil {
		return x.SnapshotsStored
	}
	return 0
}

type GetTrendingStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *TrendingStats         `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrendingStatsResponse) Reset() {
	*x = GetTrendingStatsResponse{}
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrendingStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrendingStatsResponse) ProtoMessage() {}

func (x *GetTrendingStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_trending_v1_trending_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrendingStatsResponse.ProtoReflect.Descriptor instead.
func (*GetTrendingStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_lib_trending_v1_trending_proto_rawDescGZIP(), []int{22}
}

func (x *GetTrendingStatsResponse) GetStats() *TrendingStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_proto_lib_trending_v1_trending_proto protoreflect.FileDescriptor

const file_proto_lib_trending_v1_trending_proto_rawDesc = "" +
	"\n" +
	"$proto/lib/trending/v1/trending.proto\x12\x19erg.ninja.lib.trending.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xc4\x03\n" +
	"\rTrendingTopic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12\x16\n" +
	"\x06volume\x18\x05 \x01(\x05R\x06volume\x12A\n" +
	"\x06source\x18\x06 \x01(\x0e2).erg.ninja.lib.trending.v1.TrendingSourceR\x06source\x12\x1a\n" +
	"\bkeywords\x18\a \x03(\tR\bkeywords\x12\x12\n" +
	"\x04urls\x18\b \x03(\tR\x04urls\x12\x1a\n" +
	"\btimeline\x18\t \x03(\x05R\btimeline\x12F\n" +
	"\x11last_refreshed_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x0flastRefreshedAt\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc1\x01\n" +
	"\x13GetTopTopicsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12C\n" +
	"\n" +
	"time_range\x18\x03 \x01(\x0e2$.erg.ninja.lib.trending.v1.TimeRangeR\ttimeRange\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\"\xdc\x01\n" +
	"\x14GetTopTopicsResponse\x12@\n" +
	"\x06topics\x18\x01 \x03(\v2(.erg.ninja.lib.trending.v1.TrendingTopicR\x06topics\x12=\n" +
	"\fgenerated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\x12C\n" +
	"\n" +
	"time_range\x18\x03 \x01(\x0e2$.erg.ninja.lib.trending.v1.TimeRangeR\ttimeRange\"X\n" +
	"\x0fGetTopicRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\"R\n" +
	"\x10GetTopicResponse\x12>\n" +
	"\x05topic\x18\x01 \x01(\v2(.erg.ninja.lib.trending.v1.TrendingTopicR\x05topic\"^\n" +
	"\x13SearchTopicsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"X\n" +
	"\x14SearchTopicsResponse\x12@\n" +
	"\x06topics\x18\x01 \x03(\v2(.erg.ninja.lib.trending.v1.TrendingTopicR\x06topics\"\xd7\x02\n" +
	"\vNewsArticle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1a\n" +
	"\bheadline\x18\x03 \x01(\tR\bheadline\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12=\n" +
	"\fpublished_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x12'\n" +
	"\x0frelevance_score\x18\a \x01(\x01R\x0erelevanceScore\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"v\n" +
	"\x13GetTopicNewsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"Z\n" +
	"\x14GetTopicNewsResponse\x12B\n" +
	"\barticles\x18\x01 \x03(\v2&.erg.ninja.lib.trending.v1.NewsArticleR\barticles\"\xff\x01\n" +
	"\x10TrendingSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12@\n" +
	"\x06topics\x18\x02 \x03(\v2(.erg.ninja.lib.trending.v1.TrendingTopicR\x06topics\x12\x1f\n" +
	"\vtopic_count\x18\x03 \x01(\x05R\n" +
	"topicCount\x12=\n" +
	"\fgenerated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"R\n" +
	"\x12GetSnapshotRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vsnapshot_id\x18\x02 \x01(\tR\n" +
	"snapshotId\"^\n" +
	"\x13GetSnapshotResponse\x12G\n" +
	"\bsnapshot\x18\x01 \x01(\v2+.erg.ninja.lib.trending.v1.TrendingSnapshotR\bsnapshot\"|\n" +
	"\x18GetLatestSnapshotRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12C\n" +
	"\n" +
	"time_range\x18\x02 \x01(\x0e2$.erg.ninja.lib.trending.v1.TimeRangeR\ttimeRange\"d\n" +
	"\x19GetLatestSnapshotResponse\x12G\n" +
	"\bsnapshot\x18\x01 \x01(\v2+.erg.ninja.lib.trending.v1.TrendingSnapshotR\bsnapshot\"\x8e\x01\n" +
	"\x16RefreshTrendingRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12A\n" +
	"\x06source\x18\x02 \x01(\x0e2).erg.ninja.lib.trending.v1.TrendingSourceR\x06source\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\"\xca\x01\n" +
	"\x17RefreshTrendingResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vtopic_count\x18\x02 \x01(\x05R\n" +
	"topicCount\x12\x1d\n" +
	"\n" +
	"news_count\x18\x03 \x01(\x05R\tnewsCount\x12=\n" +
	"\fgenerated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\xaa\x01\n" +
	"\x16GetKeywordTrendRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x12C\n" +
	"\n" +
	"time_range\x18\x03 \x01(\x0e2$.erg.ninja.lib.trending.v1.TimeRangeR\ttimeRange\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"{\n" +
	"\x11KeywordTrendPoint\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x16\n" +
	"\x06volume\x18\x02 \x01(\x05R\x06volume\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\"\xbe\x01\n" +
	"\x17GetKeywordTrendResponse\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12C\n" +
	"\n" +
	"time_range\x18\x02 \x01(\x0e2$.erg.ninja.lib.trending.v1.TimeRangeR\ttimeRange\x12D\n" +
	"\x06points\x18\x03 \x03(\v2,.erg.ninja.lib.trending.v1.KeywordTrendPointR\x06points\"6\n" +
	"\x17GetTrendingStatsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"\xed\x01\n" +
	"\rTrendingStats\x12!\n" +
	"\ftotal_topics\x18\x01 \x01(\x05R\vtotalTopics\x12%\n" +
	"\x0eactive_sources\x18\x02 \x01(\x05R\ractiveSources\x12B\n" +
	"\x0flast_refresh_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\rlastRefreshAt\x12#\n" +
	"\rnews_articles\x18\x04 \x01(\x05R\fnewsArticles\x12)\n" +
	"\x10snapshots_stored\x18\x05 \x01(\x05R\x0fsnapshotsStored\"Z\n" +
	"\x18GetTrendingStatsResponse\x12>\n" +
	"\x05stats\x18\x01 \x01(\v2(.erg.ninja.lib.trending.v1.TrendingStatsR\x05stats*\xc2\x01\n" +
	"\x0eTrendingSource\x12\x1f\n" +
	"\x1bTRENDING_SOURCE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16TRENDING_SOURCE_GOOGLE\x10\x01\x12\x1c\n" +
	"\x18TRENDING_SOURCE_NEWS_API\x10\x02\x12\x1a\n" +
	"\x16TRENDING_SOURCE_REDDIT\x10\x03\x12\x1b\n" +
	"\x17TRENDING_SOURCE_TWITTER\x10\x04\x12\x1c\n" +
	"\x18TRENDING_SOURCE_INTERNAL\x10\x05*\x83\x01\n" +
	"\tTimeRange\x12\x1a\n" +
	"\x16TIME_RANGE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TIME_RANGE_HOURLY\x10\x01\x12\x14\n" +
	"\x10TIME_RANGE_DAILY\x10\x02\x12\x15\n" +
	"\x11TIME_RANGE_WEEKLY\x10\x03\x12\x16\n" +
	"\x12TIME_RANGE_MONTHLY\x10\x042\x98\b\n" +
	"\x0fTrendingService\x12o\n" +
	"\fGetTopTopics\x12..erg.ninja.lib.trending.v1.GetTopTopicsRequest\x1a/.erg.ninja.lib.trending.v1.GetTopTopicsResponse\x12c\n" +
	"\bGetTopic\x12*.erg.ninja.lib.trending.v1.GetTopicRequest\x1a+.erg.ninja.lib.trending.v1.GetTopicResponse\x12o\n" +
	"\fSearchTopics\x12..erg.ninja.lib.trending.v1.SearchTopicsRequest\x1a/.erg.ninja.lib.trending.v1.SearchTopicsResponse\x12o\n" +
	"\fGetTopicNews\x12..erg.ninja.lib.trending.v1.GetTopicNewsRequest\x1a/.erg.ninja.lib.trending.v1.GetTopicNewsResponse\x12l\n" +
	"\vGetSnapshot\x12-.erg.ninja.lib.trending.v1.GetSnapshotRequest\x1a..erg.ninja.lib.trending.v1.GetSnapshotResponse\x12~\n" +
	"\x11GetLatestSnapshot\x123.erg.ninja.lib.trending.v1.GetLatestSnapshotRequest\x1a4.erg.ninja.lib.trending.v1.GetLatestSnapshotResponse\x12p\n" +
	"\aRefresh\x121.erg.ninja.lib.trending.v1.RefreshTrendingRequest\x1a2.erg.ninja.lib.trending.v1.RefreshTrendingResponse\x12x\n" +
	"\x0fGetKeywordTrend\x121.erg.ninja.lib.trending.v1.GetKeywordTrendRequest\x1a2.erg.ninja.lib.trending.v1.GetKeywordTrendResponse\x12s\n" +
	"\bGetStats\x122.erg.ninja.lib.trending.v1.GetTrendingStatsRequest\x1a3.erg.ninja.lib.trending.v1.GetTrendingStatsResponseB&Z$erg.ninja/lib/trending/v1;trendingv1b\x06proto3"

var (
	file_proto_lib_trending_v1_trending_proto_rawDescOnce sync.Once
	file_proto_lib_trending_v1_trending_proto_rawDescData []byte
)

func file_proto_lib_trending_v1_trending_proto_rawDescGZIP() []byte {
	file_proto_lib_trending_v1_trending_proto_rawDescOnce.Do(func() {
		file_proto_lib_trending_v1_trending_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_lib_trending_v1_trending_proto_rawDesc), len(file_proto_lib_trending_v1_trending_proto_rawDesc)))
	})
	return file_proto_lib_trending_v1_trending_proto_rawDescData
}

var file_proto_lib_trending_v1_trending_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_lib_trending_v1_trending_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_proto_lib_trending_v1_trending_proto_goTypes = []any{
	(TrendingSource)(0),               // 0: erg.ninja.lib.trending.v1.TrendingSource
	(TimeRange)(0),                    // 1: erg.ninja.lib.trending.v1.TimeRange
	(*TrendingTopic)(nil),             // 2: erg.ninja.lib.trending.v1.TrendingTopic
	(*GetTopTopicsRequest)(nil),       // 3: erg.ninja.lib.trending.v1.GetTopTopicsRequest
	(*GetTopTopicsResponse)(nil),      // 4: erg.ninja.lib.trending.v1.GetTopTopicsResponse
	(*GetTopicRequest)(nil),           // 5: erg.ninja.lib.trending.v1.GetTopicRequest
	(*GetTopicResponse)(nil),          // 6: erg.ninja.lib.trending.v1.GetTopicResponse
	(*SearchTopicsRequest)(nil),       // 7: erg.ninja.lib.trending.v1.SearchTopicsRequest
	(*SearchTopicsResponse)(nil),      // 8: erg.ninja.lib.trending.v1.SearchTopicsResponse
	(*NewsArticle)(nil),               // 9: erg.ninja.lib.trending.v1.NewsArticle
	(*GetTopicNewsRequest)(nil),       // 10: erg.ninja.lib.trending.v1.GetTopicNewsRequest
	(*GetTopicNewsResponse)(nil),      // 11: erg.ninja.lib.trending.v1.GetTopicNewsResponse
	(*TrendingSnapshot)(nil),          // 12: erg.ninja.lib.trending.v1.TrendingSnapshot
	(*GetSnapshotRequest)(nil),        // 13: erg.ninja.lib.trending.v1.GetSnapshotRequest
	(*GetSnapshotResponse)(nil),       // 14: erg.ninja.lib.trending.v1.GetSnapshotResponse
	(*GetLatestSnapshotRequest)(nil),  // 15: erg.ninja.lib.trending.v1.GetLatestSnapshotRequest
	(*GetLatestSnapshotResponse)(nil), // 16: erg.ninja.lib.trending.v1.GetLatestSnapshotResponse
	(*RefreshTrendingRequest)(nil),    // 17: erg.ninja.lib.trending.v1.RefreshTrendingRequest
	(*RefreshTrendingResponse)(nil),   // 18: erg.ninja.lib.trending.v1.RefreshTrendingResponse
	(*GetKeywordTrendRequest)(nil),    // 19: erg.ninja.lib.trending.v1.GetKeywordTrendRequest
	(*KeywordTrendPoint)(nil),         // 20: erg.ninja.lib.trending.v1.KeywordTrendPoint
	(*GetKeywordTrendResponse)(nil),   // 21: erg.ninja.lib.trending.v1.GetKeywordTrendResponse
	(*GetTrendingStatsRequest)(nil),   // 22: erg.ninja.lib.trending.v1.GetTrendingStatsRequest
	(*TrendingStats)(nil),             // 23: erg.ninja.lib.trending.v1.TrendingStats
	(*GetTrendingStatsResponse)(nil),  // 24: erg.ninja.lib.trending.v1.GetTrendingStatsResponse
	(*timestamppb.Timestamp)(nil),     // 25: google.protobuf.Timestamp
}
var file_proto_lib_trending_v1_trending_proto_depIdxs = []int32{
	0,  // 0: erg.ninja.lib.trending.v1.TrendingTopic.source:type_name -> erg.ninja.lib.trending.v1.TrendingSource
	25, // 1: erg.ninja.lib.trending.v1.TrendingTopic.last_refreshed_at:type_name -> google.protobuf.Timestamp
	25, // 2: erg.ninja.lib.trending.v1.TrendingTopic.created_at:type_name -> google.protobuf.Timestamp
	25, // 3: erg.ninja.lib.trending.v1.TrendingTopic.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 4: erg.ninja.lib.trending.v1.GetTopTopicsRequest.time_range:type_name -> erg.ninja.lib.trending.v1.TimeRange
	2,  // 5: erg.ninja.lib.trending.v1.GetTopTopicsResponse.topics:type_name -> erg.ninja.lib.trending.v1.TrendingTopic
	25, // 6: erg.ninja.lib.trending.v1.GetTopTopicsResponse.generated_at:type_name -> google.protobuf.Timestamp
	1,  // 7: erg.ninja.lib.trending.v1.GetTopTopicsResponse.time_range:type_name -> erg.ninja.lib.trending.v1.TimeRange
	2,  // 8: erg.ninja.lib.trending.v1.GetTopicResponse.topic:type_name -> erg.ninja.lib.trending.v1.TrendingTopic
	2,  // 9: erg.ninja.lib.trending.v1.SearchTopicsResponse.topics:type_name -> erg.ninja.lib.trending.v1.TrendingTopic
	25, // 10: erg.ninja.lib.trending.v1.NewsArticle.published_at:type_name -> google.protobuf.Timestamp
	25, // 11: erg.ninja.lib.trending.v1.NewsArticle.created_at:type_name -> google.protobuf.Timestamp
	25, // 12: erg.ninja.lib.trending.v1.NewsArticle.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 13: erg.ninja.lib.trending.v1.GetTopicNewsResponse.articles:type_name -> erg.ninja.lib.trending.v1.NewsArticle
	2,  // 14: erg.ninja.lib.trending.v1.TrendingSnapshot.topics:type_name -> erg.ninja.lib.trending.v1.TrendingTopic
	25, // 15: erg.ninja.lib.trending.v1.TrendingSnapshot.generated_at:type_name -> google.protobuf.Timestamp
	25, // 16: erg.ninja.lib.trending.v1.TrendingSnapshot.created_at:type_name -> google.protobuf.Timestamp
	12, // 17: erg.ninja.lib.trending.v1.GetSnapshotResponse.snapshot:type_name -> erg.ninja.lib.trending.v1.TrendingSnapshot
	1,  // 18: erg.ninja.lib.trending.v1.GetLatestSnapshotRequest.time_range:type_name -> erg.ninja.lib.trending.v1.TimeRange
	12, // 19: erg.ninja.lib.trending.v1.GetLatestSnapshotResponse.snapshot:type_name -> erg.ninja.lib.trending.v1.TrendingSnapshot
	0,  // 20: erg.ninja.lib.trending.v1.RefreshTrendingRequest.source:type_name -> erg.ninja.lib.trending.v1.TrendingSource
	25, // 21: erg.ninja.lib.trending.v1.RefreshTrendingResponse.generated_at:type_name -> google.protobuf.Timestamp
	1,  // 22: erg.ninja.lib.trending.v1.GetKeywordTrendRequest.time_range:type_name -> erg.ninja.lib.trending.v1.TimeRange
	25, // 23: erg.ninja.lib.trending.v1.KeywordTrendPoint.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 24: erg.ninja.lib.trending.v1.GetKeywordTrendResponse.time_range:type_name -> erg.ninja.lib.trending.v1.TimeRange
	20, // 25: erg.ninja.lib.trending.v1.GetKeywordTrendResponse.points:type_name -> erg.ninja.lib.trending.v1.KeywordTrendPoint
	25, // 26: erg.ninja.lib.trending.v1.TrendingStats.last_refresh_at:type_name -> google.protobuf.Timestamp
	23, // 27: erg.ninja.lib.trending.v1.GetTrendingStatsResponse.stats:type_name -> erg.ninja.lib.trending.v1.TrendingStats
	3,  // 28: erg.ninja.lib.trending.v1.TrendingService.GetTopTopics:input_type -> erg.ninja.lib.trending.v1.GetTopTopicsRequest
	5,  // 29: erg.ninja.lib.trending.v1.TrendingService.GetTopic:input_type -> erg.ninja.lib.trending.v1.GetTopicRequest
	7,  // 30: erg.ninja.lib.trending.v1.TrendingService.SearchTopics:input_type -> erg.ninja.lib.trending.v1.SearchTopicsRequest
	10, // 31: erg.ninja.lib.trending.v1.TrendingService.GetTopicNews:input_type -> erg.ninja.lib.trending.v1.GetTopicNewsRequest
	13, // 32: erg.ninja.lib.trending.v1.TrendingService.GetSnapshot:input_type -> erg.ninja.lib.trending.v1.GetSnapshotRequest
	15, // 33: erg.ninja.lib.trending.v1.TrendingService.GetLatestSnapshot:input_type -> erg.ninja.lib.trending.v1.GetLatestSnapshotRequest
	17, // 34: erg.ninja.lib.trending.v1.TrendingService.Refresh:input_type -> erg.ninja.lib.trending.v1.RefreshTrendingRequest
	19, // 35: erg.ninja.lib.trending.v1.TrendingService.GetKeywordTrend:input_type -> erg.ninja.lib.trending.v1.GetKeywordTrendRequest
	22, // 36: erg.ninja.lib.trending.v1.TrendingService.GetStats:input_type -> erg.ninja.lib.trending.v1.GetTrendingStatsRequest
	4,  // 37: erg.ninja.lib.trending.v1.TrendingService.GetTopTopics:output_type -> erg.ninja.lib.trending.v1.GetTopTopicsResponse
	6,  // 38: erg.ninja.lib.trending.v1.TrendingService.GetTopic:output_type -> erg.ninja.lib.trending.v1.GetTopicResponse
	8,  // 39: erg.ninja.lib.trending.v1.TrendingService.SearchTopics:output_type -> erg.ninja.lib.trending.v1.SearchTopicsResponse
	11, // 40: erg.ninja.lib.trending.v1.TrendingService.GetTopicNews:output_type -> erg.ninja.lib.trending.v1.GetTopicNewsResponse
	14, // 41: erg.ninja.lib.trending.v1.TrendingService.GetSnapshot:output_type -> erg.ninja.lib.trending.v1.GetSnapshotResponse
	16, // 42: erg.ninja.lib.trending.v1.TrendingService.GetLatestSnapshot:output_type -> erg.ninja.lib.trending.v1.GetLatestSnapshotResponse
	18, // 43: erg.ninja.lib.trending.v1.TrendingService.Refresh:output_type -> erg.ninja.lib.trending.v1.RefreshTrendingResponse
	21, // 44: erg.ninja.lib.trending.v1.TrendingService.GetKeywordTrend:output_type -> erg.ninja.lib.trending.v1.GetKeywordTrendResponse
	24, // 45: erg.ninja.lib.trending.v1.TrendingService.GetStats:output_type -> erg.ninja.lib.trending.v1.GetTrendingStatsResponse
	37, // [37:46] is the sub-list for method output_type
	28, // [28:37] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_proto_lib_trending_v1_trending_proto_init() }
func file_proto_lib_trending_v1_trending_proto_init() {
	if File_proto_lib_trending_v1_trending_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_lib_trending_v1_trending_proto_rawDesc), len(file_proto_lib_trending_v1_trending_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_lib_trending_v1_trending_proto_goTypes,
		DependencyIndexes: file_proto_lib_trending_v1_trending_proto_depIdxs,
		EnumInfos:         file_proto_lib_trending_v1_trending_proto_enumTypes,
		MessageInfos:      file_proto_lib_trending_v1_trending_proto_msgTypes,
	}.Build()
	File_proto_lib_trending_v1_trending_proto = out.File
	file_proto_lib_trending_v1_trending_proto_goTypes = nil
	file_proto_lib_trending_v1_trending_proto_depIdxs = nil
}
