// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/lib/notification/v1/notification.proto

package notificationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChannelType int32

const (
	ChannelType_CHANNEL_TYPE_UNSPECIFIED ChannelType = 0
	ChannelType_CHANNEL_TYPE_DISCORD     ChannelType = 1
	ChannelType_CHANNEL_TYPE_TELEGRAM    ChannelType = 2
	ChannelType_CHANNEL_TYPE_WHATSAPP    ChannelType = 3
	ChannelType_CHANNEL_TYPE_EMAIL       ChannelType = 4
	ChannelType_CHANNEL_TYPE_SLACK       ChannelType = 5
	ChannelType_CHANNEL_TYPE_WEBHOOK     ChannelType = 6
	ChannelType_CHANNEL_TYPE_SMS         ChannelType = 7
)

// Enum value maps for ChannelType.
var (
	ChannelType_name = map[int32]string{
		0: "CHANNEL_TYPE_UNSPECIFIED",
		1: "CHANNEL_TYPE_DISCORD",
		2: "CHANNEL_TYPE_TELEGRAM",
		3: "CHANNEL_TYPE_WHATSAPP",
		4: "CHANNEL_TYPE_EMAIL",
		5: "CHANNEL_TYPE_SLACK",
		6: "CHANNEL_TYPE_WEBHOOK",
		7: "CHANNEL_TYPE_SMS",
	}
	ChannelType_value = map[string]int32{
		"CHANNEL_TYPE_UNSPECIFIED": 0,
		"CHANNEL_TYPE_DISCORD":     1,
		"CHANNEL_TYPE_TELEGRAM":    2,
		"CHANNEL_TYPE_WHATSAPP":    3,
		"CHANNEL_TYPE_EMAIL":       4,
		"CHANNEL_TYPE_SLACK":       5,
		"CHANNEL_TYPE_WEBHOOK":     6,
		"CHANNEL_TYPE_SMS":         7,
	}
)

func (x ChannelType) Enum() *ChannelType {
	p := new(ChannelType)
	*p = x
	return p
}

func (x ChannelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChannelType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_lib_notification_v1_notification_proto_enumTypes[0].Descriptor()
}

func (ChannelType) Type() protoreflect.EnumType {
	return &file_proto_lib_notification_v1_notification_proto_enumTypes[0]
}

func (x ChannelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChannelType.Descriptor instead.
func (ChannelType) EnumDescriptor() ([]byte, []int) {
	return file_proto_lib_notification_v1_notification_proto_rawDescGZIP(), []int{0}
}

type NotificationStatus int32

const (
	NotificationStatus_NOTIFICATION_STATUS_UNSPECIFIED NotificationStatus = 0
	NotificationStatus_NOTIFICATION_STATUS_PENDING     NotificationStatus = 1
	NotificationStatus_NOTIFICATION_STATUS_SENT        NotificationStatus = 2
	NotificationStatus_NOTIFICATION_STATUS_DELIVERED   NotificationStatus = 3
	NotificationStatus_NOTIFICATION_STATUS_FAILED      NotificationStatus = 4
	NotificationStatus_NOTIFICATION_STATUS_RETRYING    NotificationStatus = 5
	NotificationStatus_NOTIFICATION_STATUS_CANCELED    NotificationStatus = 6
)

// Enum value maps for NotificationStatus.
var (
	NotificationStatus_name = map[int32]string{
		0: "NOTIFICATION_STATUS_UNSPECIFIED",
		1: "NOTIFICATION_STATUS_PENDING",
		2: "NOTIFICATION_STATUS_SENT",
		3: "NOTIFICATION_STATUS_DELIVERED",
		4: "NOTIFICATION_STATUS_FAILED",
		5: "NOTIFICATION_STATUS_RETRYING",
		6: "NOTIFICATION_STATUS_CANCELED",
	}
	NotificationStatus_value = map[string]int32{
		"NOTIFICATION_STATUS_UNSPECIFIED": 0,
		"NOTIFICATION_STATUS_PENDING":     1,
		"NOTIFICATION_STATUS_SENT":        2,
		"NOTIFICATION_STATUS_DELIVERED":   3,
		"NOTIFICATION_STATUS_FAILED":      4,
		"NOTIFICATION_STATUS_RETRYING":    5,
		"NOTIFICATION_STATUS_CANCELED":    6,
	}
)

func (x NotificationStatus) Enum() *NotificationStatus {
	p := new(NotificationStatus)
	*p = x
	return p
}

func (x NotificationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_lib_notification_v1_notification_proto_enumTypes[1].Descriptor()
}

func (NotificationStatus) Type() protoreflect.EnumType {
	return &file_proto_lib_notification_v1_notification_proto_enumTypes[1]
}

func (x NotificationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationStatus.Descriptor instead.
func (NotificationStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_lib_notification_v1_notification_proto_rawDescGZIP(), []int{1}
}

type PreferenceValue int32

const (
	PreferenceValue_PREFERENCE_VALUE_UNSPECIFIED PreferenceValue = 0
	PreferenceValue_PREFERENCE_VALUE_ENABLED     PreferenceValue = 1
	PreferenceValue_PREFERENCE_VALUE_DISABLED    PreferenceValue = 2
	PreferenceValue_PREFERENCE_VALUE_DIGEST      PreferenceValue = 3
)

// Enum value maps for PreferenceValue.
var (
	PreferenceValue_name = map[int32]string{
		0: "PREFERENCE_VALUE_UNSPECIFIED",
		1: "PREFERENCE_VALUE_ENABLED",
		2: "PREFERENCE_VALUE_DISABLED",
		3: "PREFERENCE_VALUE_DIGEST",
	}
	PreferenceValue_value = map[string]int32{
		"PREFERENCE_VALUE_UNSPECIFIED": 0,
		"PREFERENCE_VALUE_ENABLED":     1,
		"PREFERENCE_VALUE_DISABLED":    2,
		"PREFERENCE_VALUE_DIGEST":      3,
	}
)

func (x PreferenceValue) Enum() *PreferenceValue {
	p := new(PreferenceValue)
	*p = x
	return p
}

func (x PreferenceValue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PreferenceValue) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_lib_notification_v1_notification_proto_enumTypes[2].Descriptor()
}

func (PreferenceValue) Type() protoreflect.EnumType {
	return &file_proto_lib_notification_v1_notification_proto_enumTypes[2]
}

func (x PreferenceValue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PreferenceValue.Descriptor instead.
func (PreferenceValue) EnumDescriptor() ([]byte, []int) {
	return file_proto_lib_notification_v1_notification_proto_rawDescGZIP(), []int{2}
}

type DigestFrequency int32

const (
	DigestFrequency_DIGEST_FREQUENCY_UNSPECIFIED DigestFrequency = 0
	DigestFrequency_DIGEST_FREQUENCY_NONE        DigestFrequency = 1
	DigestFrequency_DIGEST_FREQUENCY_DAILY       DigestFrequency = 2
	DigestFrequency_DIGEST_FREQUENCY_WEEKLY      DigestFrequency = 3
	DigestFrequency_DIGEST_FREQUENCY_MONTHLY     DigestFrequency = 4
)

// Enum value maps for DigestFrequency.
var (
	DigestFrequency_name = map[int32]string{
		0: "DIGEST_FREQUENCY_UNSPECIFIED",
		1: "DIGEST_FREQUENCY_NONE",
		2: "DIGEST_FREQUENCY_DAILY",
		3: "DIGEST_FREQUENCY_WEEKLY",
		4: "DIGEST_FREQUENCY_MONTHLY",
	}
	DigestFrequency_value = map[string]int32{
		"DIGEST_FREQUENCY_UNSPECIFIED": 0,
		"DIGEST_FREQUENCY_NONE":        1,
		"DIGEST_FREQUENCY_DAILY":       2,
		"DIGEST_FREQUENCY_WEEKLY":      3,
		"DIGEST_FREQUENCY_MONTHLY":     4,
	}
)

func (x DigestFrequency) Enum() *DigestFrequency {
	p := new(DigestFrequency)
	*p = x
	return p
}

func (x DigestFrequency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DigestFrequency) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_lib_notification_v1_notification_proto_enumTypes[3].Descriptor()
}

func (DigestFrequency) Type() protoreflect.EnumType {
	return &file_proto_lib_notification_v1_notification_proto_enumTypes[3]
}

func (x DigestFrequency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DigestFrequency.Descriptor instead.
func (DigestFrequency) EnumDescriptor() ([]byte, []int) {
	return file_proto_lib_notification_v1_notification_proto_rawDescGZIP(), []int{3}
}

type SendNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Channel       ChannelType            `protobuf:"varint,3,opt,name=channel,proto3,enum=erg.ninja.lib.notification.v1.ChannelType" json:"channel,omitempty"`
	Recipient     string                 `protobuf:"bytes,4,opt,name=recipient,proto3" json:"recipient,omitempty"` // email, phone, chat_id, or webhook URL
	Subject       string                 `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	HtmlBody      string                 `protobuf:"bytes,7,opt,name=html_body,json=htmlBody,proto3" json:"html_body,omitempty"`           // optional HTML version
	Template      string                 `protobuf:"bytes,8,opt,name=template,proto3" json:"template,omitempty"`                           // optional template name
	Data          *structpb.Struct       `protobuf:"bytes,9,opt,name=data,proto3" json:"data,omitempty"`                                   // template variables
	ScheduledAt   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"` // optional scheduled delivery
	MaxRetries    int32                  `protobuf:"varint,11,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`   // default 3
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationRequest) Reset() {
	*x = SendNotificationRequest{}
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationRequest) ProtoMessage() {}

func (x *SendNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendNotificationRequest) Descriptor() ([]byte, []int) {
	return file_proto_lib_notification_v1_notification_proto_rawDescGZIP(), []int{0}
}

func (x *SendNotificationRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SendNotificationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendNotificationRequest) GetChannel() ChannelType {
	if x != nil {
		return x.Channel
	}
	return ChannelType_CHANNEL_TYPE_UNSPECIFIED
}

func (x *SendNotificationRequest) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *SendNotificationRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendNotificationRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *SendNotificationRequest) GetHtmlBody() string {
	if x != nil {
		return x.HtmlBody
	}
	return ""
}

func (x *SendNotificationRequest) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *SendNotificationRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SendNotificationRequest) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

func (x *SendNotificationRequest) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

type SendNotificationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	Status         NotificationStatus     `protobuf:"varint,2,opt,name=status,proto3,enum=erg.ninja.lib.notification.v1.NotificationStatus" json:"status,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendNotificationResponse) Reset() {
	*x = SendNotificationResponse{}
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationResponse) ProtoMessage() {}

func (x *SendNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationResponse.ProtoReflect.Descriptor instead.
func (*SendNotificationResponse) Descriptor() ([]byte, []int) {
	return file_proto_lib_notification_v1_notification_proto_rawDescGZIP(), []int{1}
}

func (x *SendNotificationResponse) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *SendNotificationResponse) GetStatus() NotificationStatus {
	if x != nil {
		return x.Status
	}
	return NotificationStatus_NOTIFICATION_STATUS_UNSPECIFIED
}

func (x *SendNotificationResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetNotificationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	TenantId       string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetNotificationRequest) Reset() {
	*x = GetNotificationRequest{}
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationRequest) ProtoMessage() {}

func (x *GetNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationRequest) Descriptor() ([]byte, []int) {
	return file_proto_lib_notification_v1_notification_proto_rawDescGZIP(), []int{2}
}

func (x *GetNotificationRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *GetNotificationRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Channel       ChannelType            `protobuf:"varint,3,opt,name=channel,proto3,enum=erg.ninja.lib.notification.v1.ChannelType" json:"channel,omitempty"`
	Recipient     string                 `protobuf:"bytes,4,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Subject       string                 `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	Template      string                 `protobuf:"bytes,7,opt,name=template,proto3" json:"template,omitempty"`
	Status        NotificationStatus     `protobuf:"varint,8,opt,name=status,proto3,enum=erg.ninja.lib.notification.v1.NotificationStatus" json:"status,omitempty"`
	RetryCount    int32                  `protobuf:"varint,9,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	MaxRetries    int32                  `protobuf:"varint,10,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	Provider      string                 `protobuf:"bytes,11,opt,name=provider,proto3" json:"provider,omitempty"`
	Digested      bool                   `protobuf:"varint,12,opt,name=digested,proto3" json:"digested,omitempty"`
	ScheduledAt   *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	DeliveredAt   *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=delivered_at,json=deliveredAt,proto3" json:"delivered_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,19,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_proto_lib_notification_v1_notification_proto_rawDescGZIP(), []int{3}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Notification) GetChannel() ChannelType {
	if x != nil {
		return x.Channel
	}
	return ChannelType_CHANNEL_TYPE_UNSPECIFIED
}

func (x *Notification) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *Notification) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Notification) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Notification) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *Notification) GetStatus() NotificationStatus {
	if x != nil {
		return x.Status
	}
	return NotificationStatus_NOTIFICATION_STATUS_UNSPECIFIED
}

func (x *Notification) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *Notification) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *Notification) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Notification) GetDigested() bool {
	if x != nil {
		return x.Digested
	}
	return false
}

func (x *Notification) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

func (x *Notification) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *Notification) GetDeliveredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveredAt
	}
	return nil
}

func (x *Notification) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Notification) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Notification) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Notification) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type GetNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notification  *Notification          `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationResponse) Reset() {
	*x = GetNotificationResponse{}
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationResponse) ProtoMessage() {}

func (x *GetNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationResponse.ProtoReflect.Descriptor instead.
func (*GetNotificationResponse) Descriptor() ([]byte, []int) {
	return file_proto_lib_notification_v1_notification_proto_rawDescGZIP(), []int{4}
}

func (x *GetNotificationResponse) GetNotification() *Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

type ListNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Channel       ChannelType            `protobuf:"varint,3,opt,name=channel,proto3,enum=erg.ninja.lib.notification.v1.ChannelType" json:"channel,omitempty"`
	Status        NotificationStatus     `protobuf:"varint,4,opt,name=status,proto3,enum=erg.ninja.lib.notification.v1.NotificationStatus" json:"status,omitempty"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=since,proto3" json:"since,omitempty"`
	Until         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=until,proto3" json:"until,omitempty"`
	PageSize      int32                  `protobuf:"varint,7,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,8,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsRequest) Reset() {
	*x = ListNotificationsRequest{}
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsRequest) ProtoMessage() {}

func (x *ListNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsRequest.ProtoReflect.Descriptor instead.
func (*ListNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_lib_notification_v1_notification_proto_rawDescGZIP(), []int{5}
}

func (x *ListNotificationsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListNotificationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListNotificationsRequest) GetChannel() ChannelType {
	if x != nil {
		return x.Channel
	}
	return ChannelType_CHANNEL_TYPE_UNSPECIFIED
}

func (x *ListNotificationsRequest) GetStatus() NotificationStatus {
	if x != nil {
		return x.Status
	}
	return NotificationStatus_NOTIFICATION_STATUS_UNSPECIFIED
}

func (x *ListNotificationsRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *ListNotificationsRequest) GetUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.Until
	}
	return nil
}

func (x *ListNotificationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListNotificationsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*Notification        `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsResponse) Reset() {
	*x = ListNotificationsResponse{}
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsResponse) ProtoMessage() {}

func (x *ListNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsResponse.ProtoReflect.Descriptor instead.
func (*ListNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_lib_notification_v1_notification_proto_rawDescGZIP(), []int{6}
}

func (x *ListNotificationsResponse) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *ListNotificationsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListNotificationsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type CancelNotificationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	TenantId       string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CancelNotificationRequest) Reset() {
	*x = CancelNotificationRequest{}
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelNotificationRequest) ProtoMessage() {}

func (x *CancelNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelNotificationRequest.ProtoReflect.Descriptor instead.
func (*CancelNotificationRequest) Descriptor() ([]byte, []int) {
	return file_proto_lib_notification_v1_notification_proto_rawDescGZIP(), []int{7}
}

func (x *CancelNotificationRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *CancelNotificationRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type CancelNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Canceled      bool                   `protobuf:"varint,1,opt,name=canceled,proto3" json:"canceled,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelNotificationResponse) Reset() {
	*x = CancelNotificationResponse{}
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelNotificationResponse) ProtoMessage() {}

func (x *CancelNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelNotificationResponse.ProtoReflect.Descriptor instead.
func (*CancelNotificationResponse) Descriptor() ([]byte, []int) {
	return file_proto_lib_notification_v1_notification_proto_rawDescGZIP(), []int{8}
}

func (x *CancelNotificationResponse) GetCanceled() bool {
	if x != nil {
		return x.Canceled
	}
	return false
}

func (x *CancelNotificationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPreferencesRequest) Reset() {
	*x = GetPreferencesRequest{}
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreferencesRequest) ProtoMessage() {}

func (x *GetPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreferencesRequest.ProtoReflect.Descriptor instead.
func (*GetPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_proto_lib_notification_v1_notification_proto_rawDescGZIP(), []int{9}
}

func (x *GetPreferencesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetPreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type WebhookPref struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookPref) Reset() {
	*x = WebhookPref{}
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookPref) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookPref) ProtoMessage() {}

func (x *WebhookPref) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookPref.ProtoReflect.Descriptor instead.
func (*WebhookPref) Descriptor() ([]byte, []int) {
	return file_proto_lib_notification_v1_notification_proto_rawDescGZIP(), []int{10}
}

func (x *WebhookPref) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WebhookPref) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *WebhookPref) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type NotificationPreferences struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EmailPref     PreferenceValue        `protobuf:"varint,3,opt,name=email_pref,json=emailPref,proto3,enum=erg.ninja.lib.notification.v1.PreferenceValue" json:"email_pref,omitempty"`
	DiscordPref   PreferenceValue        `protobuf:"varint,4,opt,name=discord_pref,json=discordPref,proto3,enum=erg.ninja.lib.notification.v1.PreferenceValue" json:"discord_pref,omitempty"`
	TelegramPref  PreferenceValue        `protobuf:"varint,5,opt,name=telegram_pref,json=telegramPref,proto3,enum=erg.ninja.lib.notification.v1.PreferenceValue" json:"telegram_pref,omitempty"`
	WhatsappPref  PreferenceValue        `protobuf:"varint,6,opt,name=whatsapp_pref,json=whatsappPref,proto3,enum=erg.ninja.lib.notification.v1.PreferenceValue" json:"whatsapp_pref,omitempty"`
	SlackPref     PreferenceValue        `protobuf:"varint,7,opt,name=slack_pref,json=slackPref,proto3,enum=erg.ninja.lib.notification.v1.PreferenceValue" json:"slack_pref,omitempty"`
	Webhooks      []*WebhookPref         `protobuf:"bytes,8,rep,name=webhooks,proto3" json:"webhooks,omitempty"`
	DigestFreq    DigestFrequency        `protobuf:"varint,9,opt,name=digest_freq,json=digestFreq,proto3,enum=erg.ninja.lib.notification.v1.DigestFrequency" json:"digest_freq,omitempty"`
	DigestTime    string                 `protobuf:"bytes,10,opt,name=digest_time,json=digestTime,proto3" json:"digest_time,omitempty"` // "HH:MM"
	Language      string                 `protobuf:"bytes,11,opt,name=language,proto3" json:"language,omitempty"`                       // "vi"|"en"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationPreferences) Reset() {
	*x = NotificationPreferences{}
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationPreferences) ProtoMessage() {}

func (x *NotificationPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationPreferences.ProtoReflect.Descriptor instead.
func (*NotificationPreferences) Descriptor() ([]byte, []int) {
	return file_proto_lib_notification_v1_notification_proto_rawDescGZIP(), []int{11}
}

func (x *NotificationPreferences) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *NotificationPreferences) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NotificationPreferences) GetEmailPref() PreferenceValue {
	if x != nil {
		return x.EmailPref
	}
	return PreferenceValue_PREFERENCE_VALUE_UNSPECIFIED
}

func (x *NotificationPreferences) GetDiscordPref() PreferenceValue {
	if x != nil {
		return x.DiscordPref
	}
	return PreferenceValue_PREFERENCE_VALUE_UNSPECIFIED
}

func (x *NotificationPreferences) GetTelegramPref() PreferenceValue {
	if x != nil {
		return x.TelegramPref
	}
	return PreferenceValue_PREFERENCE_VALUE_UNSPECIFIED
}

func (x *NotificationPreferences) GetWhatsappPref() PreferenceValue {
	if x != nil {
		return x.WhatsappPref
	}
	return PreferenceValue_PREFERENCE_VALUE_UNSPECIFIED
}

func (x *NotificationPreferences) GetSlackPref() PreferenceValue {
	if x != nil {
		return x.SlackPref
	}
	return PreferenceValue_PREFERENCE_VALUE_UNSPECIFIED
}

func (x *NotificationPreferences) GetWebhooks() []*WebhookPref {
	if x != nil {
		return x.Webhooks
	}
	return nil
}

func (x *NotificationPreferences) GetDigestFreq() DigestFrequency {
	if x != nil {
		return x.DigestFreq
	}
	return DigestFrequency_DIGEST_FREQUENCY_UNSPECIFIED
}

func (x *NotificationPreferences) GetDigestTime() string {
	if x != nil {
		return x.DigestTime
	}
	return ""
}

func (x *NotificationPreferences) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type GetPreferencesResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Preferences   *NotificationPreferences `protobuf:"bytes,1,opt,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPreferencesResponse) Reset() {
	*x = GetPreferencesResponse{}
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreferencesResponse) ProtoMessage() {}

func (x *GetPreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreferencesResponse.ProtoReflect.Descriptor instead.
func (*GetPreferencesResponse) Descriptor() ([]byte, []int) {
	return file_proto_lib_notification_v1_notification_proto_rawDescGZIP(), []int{12}
}

func (x *GetPreferencesResponse) GetPreferences() *NotificationPreferences {
	if x != nil {
		return x.Preferences
	}
	return nil
}

type UpdatePreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EmailPref     PreferenceValue        `protobuf:"varint,3,opt,name=email_pref,json=emailPref,proto3,enum=erg.ninja.lib.notification.v1.PreferenceValue" json:"email_pref,omitempty"`
	DiscordPref   PreferenceValue        `protobuf:"varint,4,opt,name=discord_pref,json=discordPref,proto3,enum=erg.ninja.lib.notification.v1.PreferenceValue" json:"discord_pref,omitempty"`
	TelegramPref  PreferenceValue        `protobuf:"varint,5,opt,name=telegram_pref,json=telegramPref,proto3,enum=erg.ninja.lib.notification.v1.PreferenceValue" json:"telegram_pref,omitempty"`
	WhatsappPref  PreferenceValue        `protobuf:"varint,6,opt,name=whatsapp_pref,json=whatsappPref,proto3,enum=erg.ninja.lib.notification.v1.PreferenceValue" json:"whatsapp_pref,omitempty"`
	SlackPref     PreferenceValue        `protobuf:"varint,7,opt,name=slack_pref,json=slackPref,proto3,enum=erg.ninja.lib.notification.v1.PreferenceValue" json:"slack_pref,omitempty"`
	Webhooks      []*WebhookPref         `protobuf:"bytes,8,rep,name=webhooks,proto3" json:"webhooks,omitempty"`
	DigestFreq    DigestFrequency        `protobuf:"varint,9,opt,name=digest_freq,json=digestFreq,proto3,enum=erg.ninja.lib.notification.v1.DigestFrequency" json:"digest_freq,omitempty"`
	DigestTime    string                 `protobuf:"bytes,10,opt,name=digest_time,json=digestTime,proto3" json:"digest_time,omitempty"`
	Language      string                 `protobuf:"bytes,11,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePreferencesRequest) Reset() {
	*x = UpdatePreferencesRequest{}
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePreferencesRequest) ProtoMessage() {}

func (x *UpdatePreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePreferencesRequest.ProtoReflect.Descriptor instead.
func (*UpdatePreferencesRequest) Descriptor() ([]byte, []int) {
	return file_proto_lib_notification_v1_notification_proto_rawDescGZIP(), []int{13}
}

func (x *UpdatePreferencesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UpdatePreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdatePreferencesRequest) GetEmailPref() PreferenceValue {
	if x != nil {
		return x.EmailPref
	}
	return PreferenceValue_PREFERENCE_VALUE_UNSPECIFIED
}

func (x *UpdatePreferencesRequest) GetDiscordPref() PreferenceValue {
	if x != nil {
		return x.DiscordPref
	}
	return PreferenceValue_PREFERENCE_VALUE_UNSPECIFIED
}

func (x *UpdatePreferencesRequest) GetTelegramPref() PreferenceValue {
	if x != nil {
		return x.TelegramPref
	}
	return PreferenceValue_PREFERENCE_VALUE_UNSPECIFIED
}

func (x *UpdatePreferencesRequest) GetWhatsappPref() PreferenceValue {
	if x != nil {
		return x.WhatsappPref
	}
	return PreferenceValue_PREFERENCE_VALUE_UNSPECIFIED
}

func (x *UpdatePreferencesRequest) GetSlackPref() PreferenceValue {
	if x != nil {
		return x.SlackPref
	}
	return PreferenceValue_PREFERENCE_VALUE_UNSPECIFIED
}

func (x *UpdatePreferencesRequest) GetWebhooks() []*WebhookPref {
	if x != nil {
		return x.Webhooks
	}
	return nil
}

func (x *UpdatePreferencesRequest) GetDigestFreq() DigestFrequency {
	if x != nil {
		return x.DigestFreq
	}
	return DigestFrequency_DIGEST_FREQUENCY_UNSPECIFIED
}

func (x *UpdatePreferencesRequest) GetDigestTime() string {
	if x != nil {
		return x.DigestTime
	}
	return ""
}

func (x *UpdatePreferencesRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type UpdatePreferencesResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Preferences   *NotificationPreferences `protobuf:"bytes,1,opt,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePreferencesResponse) Reset() {
	*x = UpdatePreferencesResponse{}
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePreferencesResponse) ProtoMessage() {}

func (x *UpdatePreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePreferencesResponse.ProtoReflect.Descriptor instead.
func (*UpdatePreferencesResponse) Descriptor() ([]byte, []int) {
	return file_proto_lib_notification_v1_notification_proto_rawDescGZIP(), []int{14}
}

func (x *UpdatePreferencesResponse) GetPreferences() *NotificationPreferences {
	if x != nil {
		return x.Preferences
	}
	return nil
}

type ListDigestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Frequency     DigestFrequency        `protobuf:"varint,3,opt,name=frequency,proto3,enum=erg.ninja.lib.notification.v1.DigestFrequency" json:"frequency,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDigestsRequest) Reset() {
	*x = ListDigestsRequest{}
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDigestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDigestsRequest) ProtoMessage() {}

func (x *ListDigestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDigestsRequest.ProtoReflect.Descriptor instead.
func (*ListDigestsRequest) Descriptor() ([]byte, []int) {
	return file_proto_lib_notification_v1_notification_proto_rawDescGZIP(), []int{15}
}

func (x *ListDigestsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListDigestsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListDigestsRequest) GetFrequency() DigestFrequency {
	if x != nil {
		return x.Frequency
	}
	return DigestFrequency_DIGEST_FREQUENCY_UNSPECIFIED
}

func (x *ListDigestsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDigestsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type Digest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Channel       ChannelType            `protobuf:"varint,3,opt,name=channel,proto3,enum=erg.ninja.lib.notification.v1.ChannelType" json:"channel,omitempty"`
	Recipient     string                 `protobuf:"bytes,4,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Frequency     DigestFrequency        `protobuf:"varint,5,opt,name=frequency,proto3,enum=erg.ninja.lib.notification.v1.DigestFrequency" json:"frequency,omitempty"`
	Subject       string                 `protobuf:"bytes,6,opt,name=subject,proto3" json:"subject,omitempty"`
	Items         []string               `protobuf:"bytes,7,rep,name=items,proto3" json:"items,omitempty"`
	Count         int32                  `protobuf:"varint,8,opt,name=count,proto3" json:"count,omitempty"`
	Status        NotificationStatus     `protobuf:"varint,9,opt,name=status,proto3,enum=erg.ninja.lib.notification.v1.NotificationStatus" json:"status,omitempty"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Digest) Reset() {
	*x = Digest{}
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Digest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Digest) ProtoMessage() {}

func (x *Digest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Digest.ProtoReflect.Descriptor instead.
func (*Digest) Descriptor() ([]byte, []int) {
	return file_proto_lib_notification_v1_notification_proto_rawDescGZIP(), []int{16}
}

func (x *Digest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Digest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Digest) GetChannel() ChannelType {
	if x != nil {
		return x.Channel
	}
	return ChannelType_CHANNEL_TYPE_UNSPECIFIED
}

func (x *Digest) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *Digest) GetFrequency() DigestFrequency {
	if x != nil {
		return x.Frequency
	}
	return DigestFrequency_DIGEST_FREQUENCY_UNSPECIFIED
}

func (x *Digest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Digest) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Digest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Digest) GetStatus() NotificationStatus {
	if x != nil {
		return x.Status
	}
	return NotificationStatus_NOTIFICATION_STATUS_UNSPECIFIED
}

func (x *Digest) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *Digest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Digest) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListDigestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digests       []*Digest              `protobuf:"bytes,1,rep,name=digests,proto3" json:"digests,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDigestsResponse) Reset() {
	*x = ListDigestsResponse{}
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDigestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDigestsResponse) ProtoMessage() {}

func (x *ListDigestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDigestsResponse.ProtoReflect.Descriptor instead.
func (*ListDigestsResponse) Descriptor() ([]byte, []int) {
	return file_proto_lib_notification_v1_notification_proto_rawDescGZIP(), []int{17}
}

func (x *ListDigestsResponse) GetDigests() []*Digest {
	if x != nil {
		return x.Digests
	}
	return nil
}

func (x *ListDigestsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListDigestsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetDeliveryLogRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	TenantId       string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetDeliveryLogRequest) Reset() {
	*x = GetDeliveryLogRequest{}
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryLogRequest) ProtoMessage() {}

func (x *GetDeliveryLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryLogRequest.ProtoReflect.Descriptor instead.
func (*GetDeliveryLogRequest) Descriptor() ([]byte, []int) {
	return file_proto_lib_notification_v1_notification_proto_rawDescGZIP(), []int{18}
}

func (x *GetDeliveryLogRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *GetDeliveryLogRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type DeliveryLogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attempt       int32                  `protobuf:"varint,1,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Status        NotificationStatus     `protobuf:"varint,3,opt,name=status,proto3,enum=erg.ninja.lib.notification.v1.NotificationStatus" json:"status,omitempty"`
	HttpStatus    int32                  `protobuf:"varint,4,opt,name=http_status,json=httpStatus,proto3" json:"http_status,omitempty"`
	ResponseBody  string                 `protobuf:"bytes,5,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,6,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	DurationMs    int64                  `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryLogEntry) Reset() {
	*x = DeliveryLogEntry{}
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryLogEntry) ProtoMessage() {}

func (x *DeliveryLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryLogEntry.ProtoReflect.Descriptor instead.
func (*DeliveryLogEntry) Descriptor() ([]byte, []int) {
	return file_proto_lib_notification_v1_notification_proto_rawDescGZIP(), []int{19}
}

func (x *DeliveryLogEntry) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *DeliveryLogEntry) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *DeliveryLogEntry) GetStatus() NotificationStatus {
	if x != nil {
		return x.Status
	}
	return NotificationStatus_NOTIFICATION_STATUS_UNSPECIFIED
}

func (x *DeliveryLogEntry) GetHttpStatus() int32 {
	if x != nil {
		return x.HttpStatus
	}
	return 0
}

func (x *DeliveryLogEntry) GetResponseBody() string {
	if x != nil {
		return x.ResponseBody
	}
	return ""
}

func (x *DeliveryLogEntry) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *DeliveryLogEntry) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *DeliveryLogEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetDeliveryLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*DeliveryLogEntry    `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryLogResponse) Reset() {
	*x = GetDeliveryLogResponse{}
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryLogResponse) ProtoMessage() {}

func (x *GetDeliveryLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryLogResponse.ProtoReflect.Descriptor instead.
func (*GetDeliveryLogResponse) Descriptor() ([]byte, []int) {
	return file_proto_lib_notification_v1_notification_proto_rawDescGZIP(), []int{20}
}

func (x *GetDeliveryLogResponse) GetEntries() []*DeliveryLogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type SendBulkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Template      string                 `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	Recipients    []*BulkRecipient       `protobuf:"bytes,3,rep,name=recipients,proto3" json:"recipients,omitempty"`
	TemplateData  *structpb.Struct       `protobuf:"bytes,4,opt,name=template_data,json=templateData,proto3" json:"template_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBulkRequest) Reset() {
	*x = SendBulkRequest{}
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBulkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBulkRequest) ProtoMessage() {}

func (x *SendBulkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBulkRequest.ProtoReflect.Descriptor instead.
func (*SendBulkRequest) Descriptor() ([]byte, []int) {
	return file_proto_lib_notification_v1_notification_proto_rawDescGZIP(), []int{21}
}

func (x *SendBulkRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SendBulkRequest) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *SendBulkRequest) GetRecipients() []*BulkRecipient {
	if x != nil {
		return x.Recipients
	}
	return nil
}

func (x *SendBulkRequest) GetTemplateData() *structpb.Struct {
	if x != nil {
		return x.TemplateData
	}
	return nil
}

type BulkRecipient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Recipient     string                 `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // per-user overrides
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkRecipient) Reset() {
	*x = BulkRecipient{}
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkRecipient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkRecipient) ProtoMessage() {}

func (x *BulkRecipient) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkRecipient.ProtoReflect.Descriptor instead.
func (*BulkRecipient) Descriptor() ([]byte, []int) {
	return file_proto_lib_notification_v1_notification_proto_rawDescGZIP(), []int{22}
}

func (x *BulkRecipient) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BulkRecipient) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *BulkRecipient) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type SendBulkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SentCount     int32                  `protobuf:"varint,1,opt,name=sent_count,json=sentCount,proto3" json:"sent_count,omitempty"`
	FailedCount   int32                  `protobuf:"varint,2,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	BatchId       string                 `protobuf:"bytes,3,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBulkResponse) Reset() {
	*x = SendBulkResponse{}
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBulkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBulkResponse) ProtoMessage() {}

func (x *SendBulkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_notification_v1_notification_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBulkResponse.ProtoReflect.Descriptor instead.
func (*SendBulkResponse) Descriptor() ([]byte, []int) {
	return file_proto_lib_notification_v1_notification_proto_rawDescGZIP(), []int{23}
}

func (x *SendBulkResponse) GetSentCount() int32 {
	if x != nil {
		return x.SentCount
	}
	return 0
}

func (x *SendBulkResponse) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *SendBulkResponse) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

var File_proto_lib_notification_v1_notification_proto protoreflect.FileDescriptor

const file_proto_lib_notification_v1_notification_proto_rawDesc = "" +
	"\n" +
	",proto/lib/notification/v1/notification.proto\x12\x1derg.ninja.lib.notification.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xa7\x03\n" +
	"\x17SendNotificationRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12D\n" +
	"\achannel\x18\x03 \x01(\x0e2*.erg.ninja.lib.notification.v1.ChannelTypeR\achannel\x12\x1c\n" +
	"\trecipient\x18\x04 \x01(\tR\trecipient\x12\x18\n" +
	"\asubject\x18\x05 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x06 \x01(\tR\x04body\x12\x1b\n" +
	"\thtml_body\x18\a \x01(\tR\bhtmlBody\x12\x1a\n" +
	"\btemplate\x18\b \x01(\tR\btemplate\x12+\n" +
	"\x04data\x18\t \x01(\v2\x17.google.protobuf.StructR\x04data\x12=\n" +
	"\fscheduled_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\x12\x1f\n" +
	"\vmax_retries\x18\v \x01(\x05R\n" +
	"maxRetries\"\xc9\x01\n" +
	"\x18SendNotificationResponse\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12I\n" +
	"\x06status\x18\x02 \x01(\x0e21.erg.ninja.lib.notification.v1.NotificationStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"^\n" +
	"\x16GetNotificationRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"\xab\x06\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12D\n" +
	"\achannel\x18\x03 \x01(\x0e2*.erg.ninja.lib.notification.v1.ChannelTypeR\achannel\x12\x1c\n" +
	"\trecipient\x18\x04 \x01(\tR\trecipient\x12\x18\n" +
	"\asubject\x18\x05 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x06 \x01(\tR\x04body\x12\x1a\n" +
	"\btemplate\x18\a \x01(\tR\btemplate\x12I\n" +
	"\x06status\x18\b \x01(\x0e21.erg.ninja.lib.notification.v1.NotificationStatusR\x06status\x12\x1f\n" +
	"\vretry_count\x18\t \x01(\x05R\n" +
	"retryCount\x12\x1f\n" +
	"\vmax_retries\x18\n" +
	" \x01(\x05R\n" +
	"maxRetries\x12\x1a\n" +
	"\bprovider\x18\v \x01(\tR\bprovider\x12\x1a\n" +
	"\bdigested\x18\f \x01(\bR\bdigested\x12=\n" +
	"\fscheduled_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\x123\n" +
	"\asent_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x12=\n" +
	"\fdelivered_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\vdeliveredAt\x129\n" +
	"\n" +
	"expires_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x129\n" +
	"\n" +
	"created_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1b\n" +
	"\terror_msg\x18\x13 \x01(\tR\berrorMsg\"j\n" +
	"\x17GetNotificationResponse\x12O\n" +
	"\fnotification\x18\x01 \x01(\v2+.erg.ninja.lib.notification.v1.NotificationR\fnotification\"\x81\x03\n" +
	"\x18ListNotificationsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12D\n" +
	"\achannel\x18\x03 \x01(\x0e2*.erg.ninja.lib.notification.v1.ChannelTypeR\achannel\x12I\n" +
	"\x06status\x18\x04 \x01(\x0e21.erg.ninja.lib.notification.v1.NotificationStatusR\x06status\x120\n" +
	"\x05since\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x120\n" +
	"\x05until\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x05until\x12\x1b\n" +
	"\tpage_size\x18\a \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\b \x01(\tR\tpageToken\"\xb7\x01\n" +
	"\x19ListNotificationsResponse\x12Q\n" +
	"\rnotifications\x18\x01 \x03(\v2+.erg.ninja.lib.notification.v1.NotificationR\rnotifications\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"a\n" +
	"\x19CancelNotificationRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"R\n" +
	"\x1aCancelNotificationResponse\x12\x1a\n" +
	"\bcanceled\x18\x01 \x01(\bR\bcanceled\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"M\n" +
	"\x15GetPreferencesRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"M\n" +
	"\vWebhookPref\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\"\xc0\x05\n" +
	"\x17NotificationPreferences\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12M\n" +
	"\n" +
	"email_pref\x18\x03 \x01(\x0e2..erg.ninja.lib.notification.v1.PreferenceValueR\temailPref\x12Q\n" +
	"\fdiscord_pref\x18\x04 \x01(\x0e2..erg.ninja.lib.notification.v1.PreferenceValueR\vdiscordPref\x12S\n" +
	"\rtelegram_pref\x18\x05 \x01(\x0e2..erg.ninja.lib.notification.v1.PreferenceValueR\ftelegramPref\x12S\n" +
	"\rwhatsapp_pref\x18\x06 \x01(\x0e2..erg.ninja.lib.notification.v1.PreferenceValueR\fwhatsappPref\x12M\n" +
	"\n" +
	"slack_pref\x18\a \x01(\x0e2..erg.ninja.lib.notification.v1.PreferenceValueR\tslackPref\x12F\n" +
	"\bwebhooks\x18\b \x03(\v2*.erg.ninja.lib.notification.v1.WebhookPrefR\bwebhooks\x12O\n" +
	"\vdigest_freq\x18\t \x01(\x0e2..erg.ninja.lib.notification.v1.DigestFrequencyR\n" +
	"digestFreq\x12\x1f\n" +
	"\vdigest_time\x18\n" +
	" \x01(\tR\n" +
	"digestTime\x12\x1a\n" +
	"\blanguage\x18\v \x01(\tR\blanguage\"r\n" +
	"\x16GetPreferencesResponse\x12X\n" +
	"\vpreferences\x18\x01 \x01(\v26.erg.ninja.lib.notification.v1.NotificationPreferencesR\vpreferences\"\xc1\x05\n" +
	"\x18UpdatePreferencesRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12M\n" +
	"\n" +
	"email_pref\x18\x03 \x01(\x0e2..erg.ninja.lib.notification.v1.PreferenceValueR\temailPref\x12Q\n" +
	"\fdiscord_pref\x18\x04 \x01(\x0e2..erg.ninja.lib.notification.v1.PreferenceValueR\vdiscordPref\x12S\n" +
	"\rtelegram_pref\x18\x05 \x01(\x0e2..erg.ninja.lib.notification.v1.PreferenceValueR\ftelegramPref\x12S\n" +
	"\rwhatsapp_pref\x18\x06 \x01(\x0e2..erg.ninja.lib.notification.v1.PreferenceValueR\fwhatsappPref\x12M\n" +
	"\n" +
	"slack_pref\x18\a \x01(\x0e2..erg.ninja.lib.notification.v1.PreferenceValueR\tslackPref\x12F\n" +
	"\bwebhooks\x18\b \x03(\v2*.erg.ninja.lib.notification.v1.WebhookPrefR\bwebhooks\x12O\n" +
	"\vdigest_freq\x18\t \x01(\x0e2..erg.ninja.lib.notification.v1.DigestFrequencyR\n" +
	"digestFreq\x12\x1f\n" +
	"\vdigest_time\x18\n" +
	" \x01(\tR\n" +
	"digestTime\x12\x1a\n" +
	"\blanguage\x18\v \x01(\tR\blanguage\"u\n" +
	"\x19UpdatePreferencesResponse\x12X\n" +
	"\vpreferences\x18\x01 \x01(\v26.erg.ninja.lib.notification.v1.NotificationPreferencesR\vpreferences\"\xd4\x01\n" +
	"\x12ListDigestsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12L\n" +
	"\tfrequency\x18\x03 \x01(\x0e2..erg.ninja.lib.notification.v1.DigestFrequencyR\tfrequency\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\"\x9f\x04\n" +
	"\x06Digest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12D\n" +
	"\achannel\x18\x03 \x01(\x0e2*.erg.ninja.lib.notification.v1.ChannelTypeR\achannel\x12\x1c\n" +
	"\trecipient\x18\x04 \x01(\tR\trecipient\x12L\n" +
	"\tfrequency\x18\x05 \x01(\x0e2..erg.ninja.lib.notification.v1.DigestFrequencyR\tfrequency\x12\x18\n" +
	"\asubject\x18\x06 \x01(\tR\asubject\x12\x14\n" +
	"\x05items\x18\a \x03(\tR\x05items\x12\x14\n" +
	"\x05count\x18\b \x01(\x05R\x05count\x12I\n" +
	"\x06status\x18\t \x01(\x0e21.erg.ninja.lib.notification.v1.NotificationStatusR\x06status\x123\n" +
	"\asent_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9f\x01\n" +
	"\x13ListDigestsResponse\x12?\n" +
	"\adigests\x18\x01 \x03(\v2%.erg.ninja.lib.notification.v1.DigestR\adigests\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"]\n" +
	"\x15GetDeliveryLogRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"\xd2\x02\n" +
	"\x10DeliveryLogEntry\x12\x18\n" +
	"\aattempt\x18\x01 \x01(\x05R\aattempt\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12I\n" +
	"\x06status\x18\x03 \x01(\x0e21.erg.ninja.lib.notification.v1.NotificationStatusR\x06status\x12\x1f\n" +
	"\vhttp_status\x18\x04 \x01(\x05R\n" +
	"httpStatus\x12#\n" +
	"\rresponse_body\x18\x05 \x01(\tR\fresponseBody\x12\x1b\n" +
	"\terror_msg\x18\x06 \x01(\tR\berrorMsg\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x03R\n" +
	"durationMs\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"c\n" +
	"\x16GetDeliveryLogResponse\x12I\n" +
	"\aentries\x18\x01 \x03(\v2/.erg.ninja.lib.notification.v1.DeliveryLogEntryR\aentries\"\xd6\x01\n" +
	"\x0fSendBulkRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1a\n" +
	"\btemplate\x18\x02 \x01(\tR\btemplate\x12L\n" +
	"\n" +
	"recipients\x18\x03 \x03(\v2,.erg.ninja.lib.notification.v1.BulkRecipientR\n" +
	"recipients\x12<\n" +
	"\rtemplate_data\x18\x04 \x01(\v2\x17.google.protobuf.StructR\ftemplateData\"s\n" +
	"\rBulkRecipient\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1c\n" +
	"\trecipient\x18\x02 \x01(\tR\trecipient\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04data\"o\n" +
	"\x10SendBulkResponse\x12\x1d\n" +
	"\n" +
	"sent_count\x18\x01 \x01(\x05R\tsentCount\x12!\n" +
	"\ffailed_count\x18\x02 \x01(\x05R\vfailedCount\x12\x19\n" +
	"\bbatch_id\x18\x03 \x01(\tR\abatchId*\xdb\x01\n" +
	"\vChannelType\x12\x1c\n" +
	"\x18CHANNEL_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14CHANNEL_TYPE_DISCORD\x10\x01\x12\x19\n" +
	"\x15CHANNEL_TYPE_TELEGRAM\x10\x02\x12\x19\n" +
	"\x15CHANNEL_TYPE_WHATSAPP\x10\x03\x12\x16\n" +
	"\x12CHANNEL_TYPE_EMAIL\x10\x04\x12\x16\n" +
	"\x12CHANNEL_TYPE_SLACK\x10\x05\x12\x18\n" +
	"\x14CHANNEL_TYPE_WEBHOOK\x10\x06\x12\x14\n" +
	"\x10CHANNEL_TYPE_SMS\x10\a*\xff\x01\n" +
	"\x12NotificationStatus\x12#\n" +
	"\x1fNOTIFICATION_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bNOTIFICATION_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18NOTIFICATION_STATUS_SENT\x10\x02\x12!\n" +
	"\x1dNOTIFICATION_STATUS_DELIVERED\x10\x03\x12\x1e\n" +
	"\x1aNOTIFICATION_STATUS_FAILED\x10\x04\x12 \n" +
	"\x1cNOTIFICATION_STATUS_RETRYING\x10\x05\x12 \n" +
	"\x1cNOTIFICATION_STATUS_CANCELED\x10\x06*\x8d\x01\n" +
	"\x0fPreferenceValue\x12 \n" +
	"\x1cPREFERENCE_VALUE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18PREFERENCE_VALUE_ENABLED\x10\x01\x12\x1d\n" +
	"\x19PREFERENCE_VALUE_DISABLED\x10\x02\x12\x1b\n" +
	"\x17PREFERENCE_VALUE_DIGEST\x10\x03*\xa5\x01\n" +
	"\x0fDigestFrequency\x12 \n" +
	"\x1cDIGEST_FREQUENCY_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15DIGEST_FREQUENCY_NONE\x10\x01\x12\x1a\n" +
	"\x16DIGEST_FREQUENCY_DAILY\x10\x02\x12\x1b\n" +
	"\x17DIGEST_FREQUENCY_WEEKLY\x10\x03\x12\x1c\n" +
	"\x18DIGEST_FREQUENCY_MONTHLY\x10\x042\xe8\b\n" +
	"\x13NotificationService\x12w\n" +
	"\x04Send\x126.erg.ninja.lib.notification.v1.SendNotificationRequest\x1a7.erg.ninja.lib.notification.v1.SendNotificationResponse\x12t\n" +
	"\x03Get\x125.erg.ninja.lib.notification.v1.GetNotificationRequest\x1a6.erg.ninja.lib.notification.v1.GetNotificationResponse\x12y\n" +
	"\x04List\x127.erg.ninja.lib.notification.v1.ListNotificationsRequest\x1a8.erg.ninja.lib.notification.v1.ListNotificationsResponse\x12}\n" +
	"\x06Cancel\x128.erg.ninja.lib.notification.v1.CancelNotificationRequest\x1a9.erg.ninja.lib.notification.v1.CancelNotificationResponse\x12}\n" +
	"\x0eGetPreferences\x124.erg.ninja.lib.notification.v1.GetPreferencesRequest\x1a5.erg.ninja.lib.notification.v1.GetPreferencesResponse\x12\x86\x01\n" +
	"\x11UpdatePreferences\x127.erg.ninja.lib.notification.v1.UpdatePreferencesRequest\x1a8.erg.ninja.lib.notification.v1.UpdatePreferencesResponse\x12t\n" +
	"\vListDigests\x121.erg.ninja.lib.notification.v1.ListDigestsRequest\x1a2.erg.ninja.lib.notification.v1.ListDigestsResponse\x12}\n" +
	"\x0eGetDeliveryLog\x124.erg.ninja.lib.notification.v1.GetDeliveryLogRequest\x1a5.erg.ninja.lib.notification.v1.GetDeliveryLogResponse\x12k\n" +
	"\bSendBulk\x12..erg.ninja.lib.notification.v1.SendBulkRequest\x1a/.erg.ninja.lib.notification.v1.SendBulkResponseB.Z,erg.ninja/lib/notification/v1;notificationv1b\x06proto3"

var (
	file_proto_lib_notification_v1_notification_proto_rawDescOnce sync.Once
	file_proto_lib_notification_v1_notification_proto_rawDescData []byte
)

func file_proto_lib_notification_v1_notification_proto_rawDescGZIP() []byte {
	file_proto_lib_notification_v1_notification_proto_rawDescOnce.Do(func() {
		file_proto_lib_notification_v1_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_lib_notification_v1_notification_proto_rawDesc), len(file_proto_lib_notification_v1_notification_proto_rawDesc)))
	})
	return file_proto_lib_notification_v1_notification_proto_rawDescData
}

var file_proto_lib_notification_v1_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_lib_notification_v1_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_proto_lib_notification_v1_notification_proto_goTypes = []any{
	(ChannelType)(0),                   // 0: erg.ninja.lib.notification.v1.ChannelType
	(NotificationStatus)(0),            // 1: erg.ninja.lib.notification.v1.NotificationStatus
	(PreferenceValue)(0),               // 2: erg.ninja.lib.notification.v1.PreferenceValue
	(DigestFrequency)(0),               // 3: erg.ninja.lib.notification.v1.DigestFrequency
	(*SendNotificationRequest)(nil),    // 4: erg.ninja.lib.notification.v1.SendNotificationRequest
	(*SendNotificationResponse)(nil),   // 5: erg.ninja.lib.notification.v1.SendNotificationResponse
	(*GetNotificationRequest)(nil),     // 6: erg.ninja.lib.notification.v1.GetNotificationRequest
	(*Notification)(nil),               // 7: erg.ninja.lib.notification.v1.Notification
	(*GetNotificationResponse)(nil),    // 8: erg.ninja.lib.notification.v1.GetNotificationResponse
	(*ListNotificationsRequest)(nil),   // 9: erg.ninja.lib.notification.v1.ListNotificationsRequest
	(*ListNotificationsResponse)(nil),  // 10: erg.ninja.lib.notification.v1.ListNotificationsResponse
	(*CancelNotificationRequest)(nil),  // 11: erg.ninja.lib.notification.v1.CancelNotificationRequest
	(*CancelNotificationResponse)(nil), // 12: erg.ninja.lib.notification.v1.CancelNotificationResponse
	(*GetPreferencesRequest)(nil),      // 13: erg.ninja.lib.notification.v1.GetPreferencesRequest
	(*WebhookPref)(nil),                // 14: erg.ninja.lib.notification.v1.WebhookPref
	(*NotificationPreferences)(nil),    // 15: erg.ninja.lib.notification.v1.NotificationPreferences
	(*GetPreferencesResponse)(nil),     // 16: erg.ninja.lib.notification.v1.GetPreferencesResponse
	(*UpdatePreferencesRequest)(nil),   // 17: erg.ninja.lib.notification.v1.UpdatePreferencesRequest
	(*UpdatePreferencesResponse)(nil),  // 18: erg.ninja.lib.notification.v1.UpdatePreferencesResponse
	(*ListDigestsRequest)(nil),         // 19: erg.ninja.lib.notification.v1.ListDigestsRequest
	(*Digest)(nil),                     // 20: erg.ninja.lib.notification.v1.Digest
	(*ListDigestsResponse)(nil),        // 21: erg.ninja.lib.notification.v1.ListDigestsResponse
	(*GetDeliveryLogRequest)(nil),      // 22: erg.ninja.lib.notification.v1.GetDeliveryLogRequest
	(*DeliveryLogEntry)(nil),           // 23: erg.ninja.lib.notification.v1.DeliveryLogEntry
	(*GetDeliveryLogResponse)(nil),     // 24: erg.ninja.lib.notification.v1.GetDeliveryLogResponse
	(*SendBulkRequest)(nil),            // 25: erg.ninja.lib.notification.v1.SendBulkRequest
	(*BulkRecipient)(nil),              // 26: erg.ninja.lib.notification.v1.BulkRecipient
	(*SendBulkResponse)(nil),           // 27: erg.ninja.lib.notification.v1.SendBulkResponse
	(*structpb.Struct)(nil),            // 28: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),      // 29: google.protobuf.Timestamp
}
var file_proto_lib_notification_v1_notification_proto_depIdxs = []int32{
	0,  // 0: erg.ninja.lib.notification.v1.SendNotificationRequest.channel:type_name -> erg.ninja.lib.notification.v1.ChannelType
	28, // 1: erg.ninja.lib.notification.v1.SendNotificationRequest.data:type_name -> google.protobuf.Struct
	29, // 2: erg.ninja.lib.notification.v1.SendNotificationRequest.scheduled_at:type_name -> google.protobuf.Timestamp
	1,  // 3: erg.ninja.lib.notification.v1.SendNotificationResponse.status:type_name -> erg.ninja.lib.notification.v1.NotificationStatus
	29, // 4: erg.ninja.lib.notification.v1.SendNotificationResponse.created_at:type_name -> google.protobuf.Timestamp
	0,  // 5: erg.ninja.lib.notification.v1.Notification.channel:type_name -> erg.ninja.lib.notification.v1.ChannelType
	1,  // 6: erg.ninja.lib.notification.v1.Notification.status:type_name -> erg.ninja.lib.notification.v1.NotificationStatus
	29, // 7: erg.ninja.lib.notification.v1.Notification.scheduled_at:type_name -> google.protobuf.Timestamp
	29, // 8: erg.ninja.lib.notification.v1.Notification.sent_at:type_name -> google.protobuf.Timestamp
	29, // 9: erg.ninja.lib.notification.v1.Notification.delivered_at:type_name -> google.protobuf.Timestamp
	29, // 10: erg.ninja.lib.notification.v1.Notification.expires_at:type_name -> google.protobuf.Timestamp
	29, // 11: erg.ninja.lib.notification.v1.Notification.created_at:type_name -> google.protobuf.Timestamp
	29, // 12: erg.ninja.lib.notification.v1.Notification.updated_at:type_name -> google.protobuf.Timestamp
	7,  // 13: erg.ninja.lib.notification.v1.GetNotificationResponse.notification:type_name -> erg.ninja.lib.notification.v1.Notification
	0,  // 14: erg.ninja.lib.notification.v1.ListNotificationsRequest.channel:type_name -> erg.ninja.lib.notification.v1.ChannelType
	1,  // 15: erg.ninja.lib.notification.v1.ListNotificationsRequest.status:type_name -> erg.ninja.lib.notification.v1.NotificationStatus
	29, // 16: erg.ninja.lib.notification.v1.ListNotificationsRequest.since:type_name -> google.protobuf.Timestamp
	29, // 17: erg.ninja.lib.notification.v1.ListNotificationsRequest.until:type_name -> google.protobuf.Timestamp
	7,  // 18: erg.ninja.lib.notification.v1.ListNotificationsResponse.notifications:type_name -> erg.ninja.lib.notification.v1.Notification
	2,  // 19: erg.ninja.lib.notification.v1.NotificationPreferences.email_pref:type_name -> erg.ninja.lib.notification.v1.PreferenceValue
	2,  // 20: erg.ninja.lib.notification.v1.NotificationPreferences.discord_pref:type_name -> erg.ninja.lib.notification.v1.PreferenceValue
	2,  // 21: erg.ninja.lib.notification.v1.NotificationPreferences.telegram_pref:type_name -> erg.ninja.lib.notification.v1.PreferenceValue
	2,  // 22: erg.ninja.lib.notification.v1.NotificationPreferences.whatsapp_pref:type_name -> erg.ninja.lib.notification.v1.PreferenceValue
	2,  // 23: erg.ninja.lib.notification.v1.NotificationPreferences.slack_pref:type_name -> erg.ninja.lib.notification.v1.PreferenceValue
	14, // 24: erg.ninja.lib.notification.v1.NotificationPreferences.webhooks:type_name -> erg.ninja.lib.notification.v1.WebhookPref
	3,  // 25: erg.ninja.lib.notification.v1.NotificationPreferences.digest_freq:type_name -> erg.ninja.lib.notification.v1.DigestFrequency
	15, // 26: erg.ninja.lib.notification.v1.GetPreferencesResponse.preferences:type_name -> erg.ninja.lib.notification.v1.NotificationPreferences
	2,  // 27: erg.ninja.lib.notification.v1.UpdatePreferencesRequest.email_pref:type_name -> erg.ninja.lib.notification.v1.PreferenceValue
	2,  // 28: erg.ninja.lib.notification.v1.UpdatePreferencesRequest.discord_pref:type_name -> erg.ninja.lib.notification.v1.PreferenceValue
	2,  // 29: erg.ninja.lib.notification.v1.UpdatePreferencesRequest.telegram_pref:type_name -> erg.ninja.lib.notification.v1.PreferenceValue
	2,  // 30: erg.ninja.lib.notification.v1.UpdatePreferencesRequest.whatsapp_pref:type_name -> erg.ninja.lib.notification.v1.PreferenceValue
	2,  // 31: erg.ninja.lib.notification.v1.UpdatePreferencesRequest.slack_pref:type_name -> erg.ninja.lib.notification.v1.PreferenceValue
	14, // 32: erg.ninja.lib.notification.v1.UpdatePreferencesRequest.webhooks:type_name -> erg.ninja.lib.notification.v1.WebhookPref
	3,  // 33: erg.ninja.lib.notification.v1.UpdatePreferencesRequest.digest_freq:type_name -> erg.ninja.lib.notification.v1.DigestFrequency
	15, // 34: erg.ninja.lib.notification.v1.UpdatePreferencesResponse.preferences:type_name -> erg.ninja.lib.notification.v1.NotificationPreferences
	3,  // 35: erg.ninja.lib.notification.v1.ListDigestsRequest.frequency:type_name -> erg.ninja.lib.notification.v1.DigestFrequency
	0,  // 36: erg.ninja.lib.notification.v1.Digest.channel:type_name -> erg.ninja.lib.notification.v1.ChannelType
	3,  // 37: erg.ninja.lib.notification.v1.Digest.frequency:type_name -> erg.ninja.lib.notification.v1.DigestFrequency
	1,  // 38: erg.ninja.lib.notification.v1.Digest.status:type_name -> erg.ninja.lib.notification.v1.NotificationStatus
	29, // 39: erg.ninja.lib.notification.v1.Digest.sent_at:type_name -> google.protobuf.Timestamp
	29, // 40: erg.ninja.lib.notification.v1.Digest.created_at:type_name -> google.protobuf.Timestamp
	29, // 41: erg.ninja.lib.notification.v1.Digest.updated_at:type_name -> google.protobuf.Timestamp
	20, // 42: erg.ninja.lib.notification.v1.ListDigestsResponse.digests:type_name -> erg.ninja.lib.notification.v1.Digest
	1,  // 43: erg.ninja.lib.notification.v1.DeliveryLogEntry.status:type_name -> erg.ninja.lib.notification.v1.NotificationStatus
	29, // 44: erg.ninja.lib.notification.v1.DeliveryLogEntry.created_at:type_name -> google.protobuf.Timestamp
	23, // 45: erg.ninja.lib.notification.v1.GetDeliveryLogResponse.entries:type_name -> erg.ninja.lib.notification.v1.DeliveryLogEntry
	26, // 46: erg.ninja.lib.notification.v1.SendBulkRequest.recipients:type_name -> erg.ninja.lib.notification.v1.BulkRecipient
	28, // 47: erg.ninja.lib.notification.v1.SendBulkRequest.template_data:type_name -> google.protobuf.Struct
	28, // 48: erg.ninja.lib.notification.v1.BulkRecipient.data:type_name -> google.protobuf.Struct
	4,  // 49: erg.ninja.lib.notification.v1.NotificationService.Send:input_type -> erg.ninja.lib.notification.v1.SendNotificationRequest
	6,  // 50: erg.ninja.lib.notification.v1.NotificationService.Get:input_type -> erg.ninja.lib.notification.v1.GetNotificationRequest
	9,  // 51: erg.ninja.lib.notification.v1.NotificationService.List:input_type -> erg.ninja.lib.notification.v1.ListNotificationsRequest
	11, // 52: erg.ninja.lib.notification.v1.NotificationService.Cancel:input_type -> erg.ninja.lib.notification.v1.CancelNotificationRequest
	13, // 53: erg.ninja.lib.notification.v1.NotificationService.GetPreferences:input_type -> erg.ninja.lib.notification.v1.GetPreferencesRequest
	17, // 54: erg.ninja.lib.notification.v1.NotificationService.UpdatePreferences:input_type -> erg.ninja.lib.notification.v1.UpdatePreferencesRequest
	19, // 55: erg.ninja.lib.notification.v1.NotificationService.ListDigests:input_type -> erg.ninja.lib.notification.v1.ListDigestsRequest
	22, // 56: erg.ninja.lib.notification.v1.NotificationService.GetDeliveryLog:input_type -> erg.ninja.lib.notification.v1.GetDeliveryLogRequest
	25, // 57: erg.ninja.lib.notification.v1.NotificationService.SendBulk:input_type -> erg.ninja.lib.notification.v1.SendBulkRequest
	5,  // 58: erg.ninja.lib.notification.v1.NotificationService.Send:output_type -> erg.ninja.lib.notification.v1.SendNotificationResponse
	8,  // 59: erg.ninja.lib.notification.v1.NotificationService.Get:output_type -> erg.ninja.lib.notification.v1.GetNotificationResponse
	10, // 60: erg.ninja.lib.notification.v1.NotificationService.List:output_type -> erg.ninja.lib.notification.v1.ListNotificationsResponse
	12, // 61: erg.ninja.lib.notification.v1.NotificationService.Cancel:output_type -> erg.ninja.lib.notification.v1.CancelNotificationResponse
	16, // 62: erg.ninja.lib.notification.v1.NotificationService.GetPreferences:output_type -> erg.ninja.lib.notification.v1.GetPreferencesResponse
	18, // 63: erg.ninja.lib.notification.v1.NotificationService.UpdatePreferences:output_type -> erg.ninja.lib.notification.v1.UpdatePreferencesResponse
	21, // 64: erg.ninja.lib.notification.v1.NotificationService.ListDigests:output_type -> erg.ninja.lib.notification.v1.ListDigestsResponse
	24, // 65: erg.ninja.lib.notification.v1.NotificationService.GetDeliveryLog:output_type -> erg.ninja.lib.notification.v1.GetDeliveryLogResponse
	27, // 66: erg.ninja.lib.notification.v1.NotificationService.SendBulk:output_type -> erg.ninja.lib.notification.v1.SendBulkResponse
	58, // [58:67] is the sub-list for method output_type
	49, // [49:58] is the sub-list for method input_type
	49, // [49:49] is the sub-list for extension type_name
	49, // [49:49] is the sub-list for extension extendee
	0,  // [0:49] is the sub-list for field type_name
}

func init() { file_proto_lib_notification_v1_notification_proto_init() }
func file_proto_lib_notification_v1_notification_proto_init() {
	if File_proto_lib_notification_v1_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_lib_notification_v1_notification_proto_rawDesc), len(file_proto_lib_notification_v1_notification_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_lib_notification_v1_notification_proto_goTypes,
		DependencyIndexes: file_proto_lib_notification_v1_notification_proto_depIdxs,
		EnumInfos:         file_proto_lib_notification_v1_notification_proto_enumTypes,
		MessageInfos:      file_proto_lib_notification_v1_notification_proto_msgTypes,
	}.Build()
	File_proto_lib_notification_v1_notification_proto = out.File
	file_proto_lib_notification_v1_notification_proto_goTypes = nil
	file_proto_lib_notification_v1_notification_proto_depIdxs = nil
}
