// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/lib/crawler/v1/crawler.proto

package crawlerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CrawlStatus int32

const (
	CrawlStatus_CRAWL_STATUS_UNSPECIFIED CrawlStatus = 0
	CrawlStatus_CRAWL_STATUS_PENDING     CrawlStatus = 1
	CrawlStatus_CRAWL_STATUS_RUNNING     CrawlStatus = 2
	CrawlStatus_CRAWL_STATUS_SUCCESS     CrawlStatus = 3
	CrawlStatus_CRAWL_STATUS_FAILED      CrawlStatus = 4
	CrawlStatus_CRAWL_STATUS_CANCELED    CrawlStatus = 5
	CrawlStatus_CRAWL_STATUS_DUPLICATE   CrawlStatus = 6
	CrawlStatus_CRAWL_STATUS_BLACKLISTED CrawlStatus = 7
)

// Enum value maps for CrawlStatus.
var (
	CrawlStatus_name = map[int32]string{
		0: "CRAWL_STATUS_UNSPECIFIED",
		1: "CRAWL_STATUS_PENDING",
		2: "CRAWL_STATUS_RUNNING",
		3: "CRAWL_STATUS_SUCCESS",
		4: "CRAWL_STATUS_FAILED",
		5: "CRAWL_STATUS_CANCELED",
		6: "CRAWL_STATUS_DUPLICATE",
		7: "CRAWL_STATUS_BLACKLISTED",
	}
	CrawlStatus_value = map[string]int32{
		"CRAWL_STATUS_UNSPECIFIED": 0,
		"CRAWL_STATUS_PENDING":     1,
		"CRAWL_STATUS_RUNNING":     2,
		"CRAWL_STATUS_SUCCESS":     3,
		"CRAWL_STATUS_FAILED":      4,
		"CRAWL_STATUS_CANCELED":    5,
		"CRAWL_STATUS_DUPLICATE":   6,
		"CRAWL_STATUS_BLACKLISTED": 7,
	}
)

func (x CrawlStatus) Enum() *CrawlStatus {
	p := new(CrawlStatus)
	*p = x
	return p
}

func (x CrawlStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CrawlStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_lib_crawler_v1_crawler_proto_enumTypes[0].Descriptor()
}

func (CrawlStatus) Type() protoreflect.EnumType {
	return &file_proto_lib_crawler_v1_crawler_proto_enumTypes[0]
}

func (x CrawlStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CrawlStatus.Descriptor instead.
func (CrawlStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_lib_crawler_v1_crawler_proto_rawDescGZIP(), []int{0}
}

type FeedType int32

const (
	FeedType_FEED_TYPE_UNSPECIFIED FeedType = 0
	FeedType_FEED_TYPE_RSS         FeedType = 1
	FeedType_FEED_TYPE_ATOM        FeedType = 2
	FeedType_FEED_TYPE_JSON        FeedType = 3
)

// Enum value maps for FeedType.
var (
	FeedType_name = map[int32]string{
		0: "FEED_TYPE_UNSPECIFIED",
		1: "FEED_TYPE_RSS",
		2: "FEED_TYPE_ATOM",
		3: "FEED_TYPE_JSON",
	}
	FeedType_value = map[string]int32{
		"FEED_TYPE_UNSPECIFIED": 0,
		"FEED_TYPE_RSS":         1,
		"FEED_TYPE_ATOM":        2,
		"FEED_TYPE_JSON":        3,
	}
)

func (x FeedType) Enum() *FeedType {
	p := new(FeedType)
	*p = x
	return p
}

func (x FeedType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FeedType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_lib_crawler_v1_crawler_proto_enumTypes[1].Descriptor()
}

func (FeedType) Type() protoreflect.EnumType {
	return &file_proto_lib_crawler_v1_crawler_proto_enumTypes[1]
}

func (x FeedType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FeedType.Descriptor instead.
func (FeedType) EnumDescriptor() ([]byte, []int) {
	return file_proto_lib_crawler_v1_crawler_proto_rawDescGZIP(), []int{1}
}

type Priority int32

const (
	Priority_PRIORITY_UNSPECIFIED Priority = 0
	Priority_PRIORITY_LOW         Priority = 1
	Priority_PRIORITY_NORMAL      Priority = 2
	Priority_PRIORITY_HIGH        Priority = 3
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_UNSPECIFIED",
		1: "PRIORITY_LOW",
		2: "PRIORITY_NORMAL",
		3: "PRIORITY_HIGH",
	}
	Priority_value = map[string]int32{
		"PRIORITY_UNSPECIFIED": 0,
		"PRIORITY_LOW":         1,
		"PRIORITY_NORMAL":      2,
		"PRIORITY_HIGH":        3,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_lib_crawler_v1_crawler_proto_enumTypes[2].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_proto_lib_crawler_v1_crawler_proto_enumTypes[2]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_proto_lib_crawler_v1_crawler_proto_rawDescGZIP(), []int{2}
}

type CrawlURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                         // required: multi-tenancy isolation
	Priority      Priority               `protobuf:"varint,3,opt,name=priority,proto3,enum=erg.ninja.lib.crawler.v1.Priority" json:"priority,omitempty"` // default: PRIORITY_NORMAL
	FetchContent  bool                   `protobuf:"varint,4,opt,name=fetch_content,json=fetchContent,proto3" json:"fetch_content,omitempty"`            // fetch full HTML content
	AiEnrich      bool                   `protobuf:"varint,5,opt,name=ai_enrich,json=aiEnrich,proto3" json:"ai_enrich,omitempty"`                        // run AI content quality scoring
	FeedId        string                 `protobuf:"bytes,6,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`                               // optional: associate with RSS feed
	UserId        string                 `protobuf:"bytes,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                               // optional: initiating user
	Depth         int32                  `protobuf:"varint,8,opt,name=depth,proto3" json:"depth,omitempty"`                                              // crawl depth (0 = single page)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrawlURLRequest) Reset() {
	*x = CrawlURLRequest{}
	mi := &file_proto_lib_crawler_v1_crawler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlURLRequest) ProtoMessage() {}

func (x *CrawlURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_crawler_v1_crawler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlURLRequest.ProtoReflect.Descriptor instead.
func (*CrawlURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_lib_crawler_v1_crawler_proto_rawDescGZIP(), []int{0}
}

func (x *CrawlURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CrawlURLRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CrawlURLRequest) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *CrawlURLRequest) GetFetchContent() bool {
	if x != nil {
		return x.FetchContent
	}
	return false
}

func (x *CrawlURLRequest) GetAiEnrich() bool {
	if x != nil {
		return x.AiEnrich
	}
	return false
}

func (x *CrawlURLRequest) GetFeedId() string {
	if x != nil {
		return x.FeedId
	}
	return ""
}

func (x *CrawlURLRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CrawlURLRequest) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

type CrawlURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        CrawlStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=erg.ninja.lib.crawler.v1.CrawlStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrawlURLResponse) Reset() {
	*x = CrawlURLResponse{}
	mi := &file_proto_lib_crawler_v1_crawler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlURLResponse) ProtoMessage() {}

func (x *CrawlURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_crawler_v1_crawler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlURLResponse.ProtoReflect.Descriptor instead.
func (*CrawlURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_lib_crawler_v1_crawler_proto_rawDescGZIP(), []int{1}
}

func (x *CrawlURLResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CrawlURLResponse) GetStatus() CrawlStatus {
	if x != nil {
		return x.Status
	}
	return CrawlStatus_CRAWL_STATUS_UNSPECIFIED
}

func (x *CrawlURLResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CrawlURLResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetCrawlStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCrawlStatusRequest) Reset() {
	*x = GetCrawlStatusRequest{}
	mi := &file_proto_lib_crawler_v1_crawler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCrawlStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCrawlStatusRequest) ProtoMessage() {}

func (x *GetCrawlStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_crawler_v1_crawler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCrawlStatusRequest.ProtoReflect.Descriptor instead.
func (*GetCrawlStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_lib_crawler_v1_crawler_proto_rawDescGZIP(), []int{2}
}

func (x *GetCrawlStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetCrawlStatusRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type CrawlStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        CrawlStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=erg.ninja.lib.crawler.v1.CrawlStatus" json:"status,omitempty"`
	HttpStatus    int32                  `protobuf:"varint,3,opt,name=http_status,json=httpStatus,proto3" json:"http_status,omitempty"`
	ResponseSize  int64                  `protobuf:"varint,4,opt,name=response_size,json=responseSize,proto3" json:"response_size,omitempty"`
	DurationMs    int64                  `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	QualityScore  float64                `protobuf:"fixed64,6,opt,name=quality_score,json=qualityScore,proto3" json:"quality_score,omitempty"`
	Title         string                 `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Tags          []string               `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	Language      string                 `protobuf:"bytes,10,opt,name=language,proto3" json:"language,omitempty"`
	CrawledAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=crawled_at,json=crawledAt,proto3" json:"crawled_at,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,12,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrawlStatusResponse) Reset() {
	*x = CrawlStatusResponse{}
	mi := &file_proto_lib_crawler_v1_crawler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlStatusResponse) ProtoMessage() {}

func (x *CrawlStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_crawler_v1_crawler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlStatusResponse.ProtoReflect.Descriptor instead.
func (*CrawlStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_lib_crawler_v1_crawler_proto_rawDescGZIP(), []int{3}
}

func (x *CrawlStatusResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CrawlStatusResponse) GetStatus() CrawlStatus {
	if x != nil {
		return x.Status
	}
	return CrawlStatus_CRAWL_STATUS_UNSPECIFIED
}

func (x *CrawlStatusResponse) GetHttpStatus() int32 {
	if x != nil {
		return x.HttpStatus
	}
	return 0
}

func (x *CrawlStatusResponse) GetResponseSize() int64 {
	if x != nil {
		return x.ResponseSize
	}
	return 0
}

func (x *CrawlStatusResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *CrawlStatusResponse) GetQualityScore() float64 {
	if x != nil {
		return x.QualityScore
	}
	return 0
}

func (x *CrawlStatusResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CrawlStatusResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CrawlStatusResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CrawlStatusResponse) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *CrawlStatusResponse) GetCrawledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CrawledAt
	}
	return nil
}

func (x *CrawlStatusResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *CrawlStatusResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListFeedsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"` // optional filter
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"` // optional filter
	EnabledOnly   bool                   `protobuf:"varint,4,opt,name=enabled_only,json=enabledOnly,proto3" json:"enabled_only,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,6,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFeedsRequest) Reset() {
	*x = ListFeedsRequest{}
	mi := &file_proto_lib_crawler_v1_crawler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeedsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedsRequest) ProtoMessage() {}

func (x *ListFeedsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_crawler_v1_crawler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedsRequest.ProtoReflect.Descriptor instead.
func (*ListFeedsRequest) Descriptor() ([]byte, []int) {
	return file_proto_lib_crawler_v1_crawler_proto_rawDescGZIP(), []int{4}
}

func (x *ListFeedsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListFeedsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListFeedsRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ListFeedsRequest) GetEnabledOnly() bool {
	if x != nil {
		return x.EnabledOnly
	}
	return false
}

func (x *ListFeedsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListFeedsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type Feed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	FeedType      FeedType               `protobuf:"varint,4,opt,name=feed_type,json=feedType,proto3,enum=erg.ninja.lib.crawler.v1.FeedType" json:"feed_type,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Language      string                 `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	Frequency     string                 `protobuf:"bytes,7,opt,name=frequency,proto3" json:"frequency,omitempty"` // "5m","15m","1h","6h","daily"
	Enabled       bool                   `protobuf:"varint,8,opt,name=enabled,proto3" json:"enabled,omitempty"`
	LastFetchAt   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_fetch_at,json=lastFetchAt,proto3" json:"last_fetch_at,omitempty"`
	LastItemAt    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_item_at,json=lastItemAt,proto3" json:"last_item_at,omitempty"`
	ItemCount     int32                  `protobuf:"varint,11,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"`
	ErrorCount    int32                  `protobuf:"varint,12,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	LastError     string                 `protobuf:"bytes,13,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Feed) Reset() {
	*x = Feed{}
	mi := &file_proto_lib_crawler_v1_crawler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feed) ProtoMessage() {}

func (x *Feed) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_crawler_v1_crawler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feed.ProtoReflect.Descriptor instead.
func (*Feed) Descriptor() ([]byte, []int) {
	return file_proto_lib_crawler_v1_crawler_proto_rawDescGZIP(), []int{5}
}

func (x *Feed) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Feed) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Feed) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Feed) GetFeedType() FeedType {
	if x != nil {
		return x.FeedType
	}
	return FeedType_FEED_TYPE_UNSPECIFIED
}

func (x *Feed) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Feed) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Feed) GetFrequency() string {
	if x != nil {
		return x.Frequency
	}
	return ""
}

func (x *Feed) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Feed) GetLastFetchAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastFetchAt
	}
	return nil
}

func (x *Feed) GetLastItemAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastItemAt
	}
	return nil
}

func (x *Feed) GetItemCount() int32 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

func (x *Feed) GetErrorCount() int32 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

func (x *Feed) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *Feed) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Feed) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListFeedsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feeds         []*Feed                `protobuf:"bytes,1,rep,name=feeds,proto3" json:"feeds,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFeedsResponse) Reset() {
	*x = ListFeedsResponse{}
	mi := &file_proto_lib_crawler_v1_crawler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeedsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedsResponse) ProtoMessage() {}

func (x *ListFeedsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_crawler_v1_crawler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedsResponse.ProtoReflect.Descriptor instead.
func (*ListFeedsResponse) Descriptor() ([]byte, []int) {
	return file_proto_lib_crawler_v1_crawler_proto_rawDescGZIP(), []int{6}
}

func (x *ListFeedsResponse) GetFeeds() []*Feed {
	if x != nil {
		return x.Feeds
	}
	return nil
}

func (x *ListFeedsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListFeedsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type RefreshFeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedId        string                 `protobuf:"bytes,1,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Force         bool                   `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"` // bypass schedule check
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshFeedRequest) Reset() {
	*x = RefreshFeedRequest{}
	mi := &file_proto_lib_crawler_v1_crawler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshFeedRequest) ProtoMessage() {}

func (x *RefreshFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_crawler_v1_crawler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshFeedRequest.ProtoReflect.Descriptor instead.
func (*RefreshFeedRequest) Descriptor() ([]byte, []int) {
	return file_proto_lib_crawler_v1_crawler_proto_rawDescGZIP(), []int{7}
}

func (x *RefreshFeedRequest) GetFeedId() string {
	if x != nil {
		return x.FeedId
	}
	return ""
}

func (x *RefreshFeedRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RefreshFeedRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type RefreshFeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	NewItems      int32                  `protobuf:"varint,2,opt,name=new_items,json=newItems,proto3" json:"new_items,omitempty"`
	RefreshedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=refreshed_at,json=refreshedAt,proto3" json:"refreshed_at,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshFeedResponse) Reset() {
	*x = RefreshFeedResponse{}
	mi := &file_proto_lib_crawler_v1_crawler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshFeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshFeedResponse) ProtoMessage() {}

func (x *RefreshFeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_crawler_v1_crawler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshFeedResponse.ProtoReflect.Descriptor instead.
func (*RefreshFeedResponse) Descriptor() ([]byte, []int) {
	return file_proto_lib_crawler_v1_crawler_proto_rawDescGZIP(), []int{8}
}

func (x *RefreshFeedResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RefreshFeedResponse) GetNewItems() int32 {
	if x != nil {
		return x.NewItems
	}
	return 0
}

func (x *RefreshFeedResponse) GetRefreshedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RefreshedAt
	}
	return nil
}

func (x *RefreshFeedResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_proto_lib_crawler_v1_crawler_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_crawler_v1_crawler_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_lib_crawler_v1_crawler_proto_rawDescGZIP(), []int{9}
}

func (x *GetStatsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type StatsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalFeeds        int32                  `protobuf:"varint,1,opt,name=total_feeds,json=totalFeeds,proto3" json:"total_feeds,omitempty"`
	EnabledFeeds      int32                  `protobuf:"varint,2,opt,name=enabled_feeds,json=enabledFeeds,proto3" json:"enabled_feeds,omitempty"`
	TotalCrawls       int32                  `protobuf:"varint,3,opt,name=total_crawls,json=totalCrawls,proto3" json:"total_crawls,omitempty"`
	PendingCrawls     int32                  `protobuf:"varint,4,opt,name=pending_crawls,json=pendingCrawls,proto3" json:"pending_crawls,omitempty"`
	SuccessCrawls     int32                  `protobuf:"varint,5,opt,name=success_crawls,json=successCrawls,proto3" json:"success_crawls,omitempty"`
	FailedCrawls      int32                  `protobuf:"varint,6,opt,name=failed_crawls,json=failedCrawls,proto3" json:"failed_crawls,omitempty"`
	DuplicateCrawls   int32                  `protobuf:"varint,7,opt,name=duplicate_crawls,json=duplicateCrawls,proto3" json:"duplicate_crawls,omitempty"`
	BlacklistBlocks   int32                  `protobuf:"varint,8,opt,name=blacklist_blocks,json=blacklistBlocks,proto3" json:"blacklist_blocks,omitempty"`
	TotalBytesFetched int64                  `protobuf:"varint,9,opt,name=total_bytes_fetched,json=totalBytesFetched,proto3" json:"total_bytes_fetched,omitempty"`
	AvgDurationMs     int64                  `protobuf:"varint,10,opt,name=avg_duration_ms,json=avgDurationMs,proto3" json:"avg_duration_ms,omitempty"`
	LastRefreshAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_refresh_at,json=lastRefreshAt,proto3" json:"last_refresh_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_proto_lib_crawler_v1_crawler_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_crawler_v1_crawler_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_lib_crawler_v1_crawler_proto_rawDescGZIP(), []int{10}
}

func (x *StatsResponse) GetTotalFeeds() int32 {
	if x != nil {
		return x.TotalFeeds
	}
	return 0
}

func (x *StatsResponse) GetEnabledFeeds() int32 {
	if x != nil {
		return x.EnabledFeeds
	}
	return 0
}

func (x *StatsResponse) GetTotalCrawls() int32 {
	if x != nil {
		return x.TotalCrawls
	}
	return 0
}

func (x *StatsResponse) GetPendingCrawls() int32 {
	if x != nil {
		return x.PendingCrawls
	}
	return 0
}

func (x *StatsResponse) GetSuccessCrawls() int32 {
	if x != nil {
		return x.SuccessCrawls
	}
	return 0
}

func (x *StatsResponse) GetFailedCrawls() int32 {
	if x != nil {
		return x.FailedCrawls
	}
	return 0
}

func (x *StatsResponse) GetDuplicateCrawls() int32 {
	if x != nil {
		return x.DuplicateCrawls
	}
	return 0
}

func (x *StatsResponse) GetBlacklistBlocks() int32 {
	if x != nil {
		return x.BlacklistBlocks
	}
	return 0
}

func (x *StatsResponse) GetTotalBytesFetched() int64 {
	if x != nil {
		return x.TotalBytesFetched
	}
	return 0
}

func (x *StatsResponse) GetAvgDurationMs() int64 {
	if x != nil {
		return x.AvgDurationMs
	}
	return 0
}

func (x *StatsResponse) GetLastRefreshAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRefreshAt
	}
	return nil
}

type StopCrawlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopCrawlRequest) Reset() {
	*x = StopCrawlRequest{}
	mi := &file_proto_lib_crawler_v1_crawler_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopCrawlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopCrawlRequest) ProtoMessage() {}

func (x *StopCrawlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_crawler_v1_crawler_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopCrawlRequest.ProtoReflect.Descriptor instead.
func (*StopCrawlRequest) Descriptor() ([]byte, []int) {
	return file_proto_lib_crawler_v1_crawler_proto_rawDescGZIP(), []int{11}
}

func (x *StopCrawlRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *StopCrawlRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type StopCrawlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stopped       bool                   `protobuf:"varint,1,opt,name=stopped,proto3" json:"stopped,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopCrawlResponse) Reset() {
	*x = StopCrawlResponse{}
	mi := &file_proto_lib_crawler_v1_crawler_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopCrawlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopCrawlResponse) ProtoMessage() {}

func (x *StopCrawlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_crawler_v1_crawler_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopCrawlResponse.ProtoReflect.Descriptor instead.
func (*StopCrawlResponse) Descriptor() ([]byte, []int) {
	return file_proto_lib_crawler_v1_crawler_proto_rawDescGZIP(), []int{12}
}

func (x *StopCrawlResponse) GetStopped() bool {
	if x != nil {
		return x.Stopped
	}
	return false
}

func (x *StopCrawlResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CrawlHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	FeedId        string                 `protobuf:"bytes,2,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`
	Status        CrawlStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=erg.ninja.lib.crawler.v1.CrawlStatus" json:"status,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrawlHistoryRequest) Reset() {
	*x = CrawlHistoryRequest{}
	mi := &file_proto_lib_crawler_v1_crawler_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlHistoryRequest) ProtoMessage() {}

func (x *CrawlHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_crawler_v1_crawler_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlHistoryRequest.ProtoReflect.Descriptor instead.
func (*CrawlHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_lib_crawler_v1_crawler_proto_rawDescGZIP(), []int{13}
}

func (x *CrawlHistoryRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CrawlHistoryRequest) GetFeedId() string {
	if x != nil {
		return x.FeedId
	}
	return ""
}

func (x *CrawlHistoryRequest) GetStatus() CrawlStatus {
	if x != nil {
		return x.Status
	}
	return CrawlStatus_CRAWL_STATUS_UNSPECIFIED
}

func (x *CrawlHistoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *CrawlHistoryRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type CrawlHistoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	FeedId        string                 `protobuf:"bytes,3,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`
	Status        CrawlStatus            `protobuf:"varint,4,opt,name=status,proto3,enum=erg.ninja.lib.crawler.v1.CrawlStatus" json:"status,omitempty"`
	HttpStatus    int32                  `protobuf:"varint,5,opt,name=http_status,json=httpStatus,proto3" json:"http_status,omitempty"`
	ResponseSize  int64                  `protobuf:"varint,6,opt,name=response_size,json=responseSize,proto3" json:"response_size,omitempty"`
	DurationMs    int64                  `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	QualityScore  float64                `protobuf:"fixed64,8,opt,name=quality_score,json=qualityScore,proto3" json:"quality_score,omitempty"`
	Title         string                 `protobuf:"bytes,9,opt,name=title,proto3" json:"title,omitempty"`
	Tags          []string               `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	Language      string                 `protobuf:"bytes,11,opt,name=language,proto3" json:"language,omitempty"`
	CrawledAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=crawled_at,json=crawledAt,proto3" json:"crawled_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrawlHistoryItem) Reset() {
	*x = CrawlHistoryItem{}
	mi := &file_proto_lib_crawler_v1_crawler_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlHistoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlHistoryItem) ProtoMessage() {}

func (x *CrawlHistoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_crawler_v1_crawler_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlHistoryItem.ProtoReflect.Descriptor instead.
func (*CrawlHistoryItem) Descriptor() ([]byte, []int) {
	return file_proto_lib_crawler_v1_crawler_proto_rawDescGZIP(), []int{14}
}

func (x *CrawlHistoryItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CrawlHistoryItem) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CrawlHistoryItem) GetFeedId() string {
	if x != nil {
		return x.FeedId
	}
	return ""
}

func (x *CrawlHistoryItem) GetStatus() CrawlStatus {
	if x != nil {
		return x.Status
	}
	return CrawlStatus_CRAWL_STATUS_UNSPECIFIED
}

func (x *CrawlHistoryItem) GetHttpStatus() int32 {
	if x != nil {
		return x.HttpStatus
	}
	return 0
}

func (x *CrawlHistoryItem) GetResponseSize() int64 {
	if x != nil {
		return x.ResponseSize
	}
	return 0
}

func (x *CrawlHistoryItem) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *CrawlHistoryItem) GetQualityScore() float64 {
	if x != nil {
		return x.QualityScore
	}
	return 0
}

func (x *CrawlHistoryItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CrawlHistoryItem) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CrawlHistoryItem) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *CrawlHistoryItem) GetCrawledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CrawledAt
	}
	return nil
}

type CrawlHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CrawlHistoryItem    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrawlHistoryResponse) Reset() {
	*x = CrawlHistoryResponse{}
	mi := &file_proto_lib_crawler_v1_crawler_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlHistoryResponse) ProtoMessage() {}

func (x *CrawlHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_crawler_v1_crawler_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlHistoryResponse.ProtoReflect.Descriptor instead.
func (*CrawlHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_lib_crawler_v1_crawler_proto_rawDescGZIP(), []int{15}
}

func (x *CrawlHistoryResponse) GetItems() []*CrawlHistoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CrawlHistoryResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *CrawlHistoryResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type ReindexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Algorithm     string                 `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"` // "simhash"|"sha256"|"all"
	Since         string                 `protobuf:"bytes,3,opt,name=since,proto3" json:"since,omitempty"`         // ISO timestamp, optional
	BatchSize     int32                  `protobuf:"varint,4,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReindexRequest) Reset() {
	*x = ReindexRequest{}
	mi := &file_proto_lib_crawler_v1_crawler_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReindexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReindexRequest) ProtoMessage() {}

func (x *ReindexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_crawler_v1_crawler_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReindexRequest.ProtoReflect.Descriptor instead.
func (*ReindexRequest) Descriptor() ([]byte, []int) {
	return file_proto_lib_crawler_v1_crawler_proto_rawDescGZIP(), []int{16}
}

func (x *ReindexRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ReindexRequest) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *ReindexRequest) GetSince() string {
	if x != nil {
		return x.Since
	}
	return ""
}

func (x *ReindexRequest) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

type ReindexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReindexResponse) Reset() {
	*x = ReindexResponse{}
	mi := &file_proto_lib_crawler_v1_crawler_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReindexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReindexResponse) ProtoMessage() {}

func (x *ReindexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lib_crawler_v1_crawler_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReindexResponse.ProtoReflect.Descriptor instead.
func (*ReindexResponse) Descriptor() ([]byte, []int) {
	return file_proto_lib_crawler_v1_crawler_proto_rawDescGZIP(), []int{17}
}

func (x *ReindexResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ReindexResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ReindexResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_lib_crawler_v1_crawler_proto protoreflect.FileDescriptor

const file_proto_lib_crawler_v1_crawler_proto_rawDesc = "" +
	"\n" +
	"\"proto/lib/crawler/v1/crawler.proto\x12\x18erg.ninja.lib.crawler.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8a\x02\n" +
	"\x0fCrawlURLRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12>\n" +
	"\bpriority\x18\x03 \x01(\x0e2\".erg.ninja.lib.crawler.v1.PriorityR\bpriority\x12#\n" +
	"\rfetch_content\x18\x04 \x01(\bR\ffetchContent\x12\x1b\n" +
	"\tai_enrich\x18\x05 \x01(\bR\baiEnrich\x12\x17\n" +
	"\afeed_id\x18\x06 \x01(\tR\x06feedId\x12\x17\n" +
	"\auser_id\x18\a \x01(\tR\x06userId\x12\x14\n" +
	"\x05depth\x18\b \x01(\x05R\x05depth\"\xbd\x01\n" +
	"\x10CrawlURLResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12=\n" +
	"\x06status\x18\x02 \x01(\x0e2%.erg.ninja.lib.crawler.v1.CrawlStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"K\n" +
	"\x15GetCrawlStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"\xf2\x03\n" +
	"\x13CrawlStatusResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12=\n" +
	"\x06status\x18\x02 \x01(\x0e2%.erg.ninja.lib.crawler.v1.CrawlStatusR\x06status\x12\x1f\n" +
	"\vhttp_status\x18\x03 \x01(\x05R\n" +
	"httpStatus\x12#\n" +
	"\rresponse_size\x18\x04 \x01(\x03R\fresponseSize\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x03R\n" +
	"durationMs\x12#\n" +
	"\rquality_score\x18\x06 \x01(\x01R\fqualityScore\x12\x14\n" +
	"\x05title\x18\a \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\x12\x1a\n" +
	"\blanguage\x18\n" +
	" \x01(\tR\blanguage\x129\n" +
	"\n" +
	"crawled_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcrawledAt\x12\x1b\n" +
	"\terror_msg\x18\f \x01(\tR\berrorMsg\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xc6\x01\n" +
	"\x10ListFeedsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12!\n" +
	"\fenabled_only\x18\x04 \x01(\bR\venabledOnly\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x06 \x01(\tR\tpageToken\"\xc0\x04\n" +
	"\x04Feed\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12?\n" +
	"\tfeed_type\x18\x04 \x01(\x0e2\".erg.ninja.lib.crawler.v1.FeedTypeR\bfeedType\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x1a\n" +
	"\blanguage\x18\x06 \x01(\tR\blanguage\x12\x1c\n" +
	"\tfrequency\x18\a \x01(\tR\tfrequency\x12\x18\n" +
	"\aenabled\x18\b \x01(\bR\aenabled\x12>\n" +
	"\rlast_fetch_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vlastFetchAt\x12<\n" +
	"\flast_item_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastItemAt\x12\x1d\n" +
	"\n" +
	"item_count\x18\v \x01(\x05R\titemCount\x12\x1f\n" +
	"\verror_count\x18\f \x01(\x05R\n" +
	"errorCount\x12\x1d\n" +
	"\n" +
	"last_error\x18\r \x01(\tR\tlastError\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x92\x01\n" +
	"\x11ListFeedsResponse\x124\n" +
	"\x05feeds\x18\x01 \x03(\v2\x1e.erg.ninja.lib.crawler.v1.FeedR\x05feeds\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"`\n" +
	"\x12RefreshFeedRequest\x12\x17\n" +
	"\afeed_id\x18\x01 \x01(\tR\x06feedId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\"\xa2\x01\n" +
	"\x13RefreshFeedResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tnew_items\x18\x02 \x01(\x05R\bnewItems\x12=\n" +
	"\frefreshed_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vrefreshedAt\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\".\n" +
	"\x0fGetStatsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"\xdd\x03\n" +
	"\rStatsResponse\x12\x1f\n" +
	"\vtotal_feeds\x18\x01 \x01(\x05R\n" +
	"totalFeeds\x12#\n" +
	"\renabled_feeds\x18\x02 \x01(\x05R\fenabledFeeds\x12!\n" +
	"\ftotal_crawls\x18\x03 \x01(\x05R\vtotalCrawls\x12%\n" +
	"\x0epending_crawls\x18\x04 \x01(\x05R\rpendingCrawls\x12%\n" +
	"\x0esuccess_crawls\x18\x05 \x01(\x05R\rsuccessCrawls\x12#\n" +
	"\rfailed_crawls\x18\x06 \x01(\x05R\ffailedCrawls\x12)\n" +
	"\x10duplicate_crawls\x18\a \x01(\x05R\x0fduplicateCrawls\x12)\n" +
	"\x10blacklist_blocks\x18\b \x01(\x05R\x0fblacklistBlocks\x12.\n" +
	"\x13total_bytes_fetched\x18\t \x01(\x03R\x11totalBytesFetched\x12&\n" +
	"\x0favg_duration_ms\x18\n" +
	" \x01(\x03R\ravgDurationMs\x12B\n" +
	"\x0flast_refresh_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\rlastRefreshAt\"F\n" +
	"\x10StopCrawlRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"G\n" +
	"\x11StopCrawlResponse\x12\x18\n" +
	"\astopped\x18\x01 \x01(\bR\astopped\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc6\x01\n" +
	"\x13CrawlHistoryRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\afeed_id\x18\x02 \x01(\tR\x06feedId\x12=\n" +
	"\x06status\x18\x03 \x01(\x0e2%.erg.ninja.lib.crawler.v1.CrawlStatusR\x06status\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\"\x99\x03\n" +
	"\x10CrawlHistoryItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x17\n" +
	"\afeed_id\x18\x03 \x01(\tR\x06feedId\x12=\n" +
	"\x06status\x18\x04 \x01(\x0e2%.erg.ninja.lib.crawler.v1.CrawlStatusR\x06status\x12\x1f\n" +
	"\vhttp_status\x18\x05 \x01(\x05R\n" +
	"httpStatus\x12#\n" +
	"\rresponse_size\x18\x06 \x01(\x03R\fresponseSize\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x03R\n" +
	"durationMs\x12#\n" +
	"\rquality_score\x18\b \x01(\x01R\fqualityScore\x12\x14\n" +
	"\x05title\x18\t \x01(\tR\x05title\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x03(\tR\x04tags\x12\x1a\n" +
	"\blanguage\x18\v \x01(\tR\blanguage\x129\n" +
	"\n" +
	"crawled_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcrawledAt\"\xa1\x01\n" +
	"\x14CrawlHistoryResponse\x12@\n" +
	"\x05items\x18\x01 \x03(\v2*.erg.ninja.lib.crawler.v1.CrawlHistoryItemR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"\x80\x01\n" +
	"\x0eReindexRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\tR\talgorithm\x12\x14\n" +
	"\x05since\x18\x03 \x01(\tR\x05since\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x04 \x01(\x05R\tbatchSize\"}\n" +
	"\x0fReindexResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x129\n" +
	"\n" +
	"started_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage*\xe7\x01\n" +
	"\vCrawlStatus\x12\x1c\n" +
	"\x18CRAWL_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14CRAWL_STATUS_PENDING\x10\x01\x12\x18\n" +
	"\x14CRAWL_STATUS_RUNNING\x10\x02\x12\x18\n" +
	"\x14CRAWL_STATUS_SUCCESS\x10\x03\x12\x17\n" +
	"\x13CRAWL_STATUS_FAILED\x10\x04\x12\x19\n" +
	"\x15CRAWL_STATUS_CANCELED\x10\x05\x12\x1a\n" +
	"\x16CRAWL_STATUS_DUPLICATE\x10\x06\x12\x1c\n" +
	"\x18CRAWL_STATUS_BLACKLISTED\x10\a*`\n" +
	"\bFeedType\x12\x19\n" +
	"\x15FEED_TYPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rFEED_TYPE_RSS\x10\x01\x12\x12\n" +
	"\x0eFEED_TYPE_ATOM\x10\x02\x12\x12\n" +
	"\x0eFEED_TYPE_JSON\x10\x03*^\n" +
	"\bPriority\x12\x18\n" +
	"\x14PRIORITY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPRIORITY_LOW\x10\x01\x12\x13\n" +
	"\x0fPRIORITY_NORMAL\x10\x02\x12\x11\n" +
	"\rPRIORITY_HIGH\x10\x032\xcf\x06\n" +
	"\x0eCrawlerService\x12a\n" +
	"\bCrawlURL\x12).erg.ninja.lib.crawler.v1.CrawlURLRequest\x1a*.erg.ninja.lib.crawler.v1.CrawlURLResponse\x12p\n" +
	"\x0eGetCrawlStatus\x12/.erg.ninja.lib.crawler.v1.GetCrawlStatusRequest\x1a-.erg.ninja.lib.crawler.v1.CrawlStatusResponse\x12d\n" +
	"\tListFeeds\x12*.erg.ninja.lib.crawler.v1.ListFeedsRequest\x1a+.erg.ninja.lib.crawler.v1.ListFeedsResponse\x12j\n" +
	"\vRefreshFeed\x12,.erg.ninja.lib.crawler.v1.RefreshFeedRequest\x1a-.erg.ninja.lib.crawler.v1.RefreshFeedResponse\x12^\n" +
	"\bGetStats\x12).erg.ninja.lib.crawler.v1.GetStatsRequest\x1a'.erg.ninja.lib.crawler.v1.StatsResponse\x12d\n" +
	"\tStopCrawl\x12*.erg.ninja.lib.crawler.v1.StopCrawlRequest\x1a+.erg.ninja.lib.crawler.v1.StopCrawlResponse\x12p\n" +
	"\x0fGetCrawlHistory\x12-.erg.ninja.lib.crawler.v1.CrawlHistoryRequest\x1a..erg.ninja.lib.crawler.v1.CrawlHistoryResponse\x12^\n" +
	"\aReindex\x12(.erg.ninja.lib.crawler.v1.ReindexRequest\x1a).erg.ninja.lib.crawler.v1.ReindexResponseB$Z\"erg.ninja/lib/crawler/v1;crawlerv1b\x06proto3"

var (
	file_proto_lib_crawler_v1_crawler_proto_rawDescOnce sync.Once
	file_proto_lib_crawler_v1_crawler_proto_rawDescData []byte
)

func file_proto_lib_crawler_v1_crawler_proto_rawDescGZIP() []byte {
	file_proto_lib_crawler_v1_crawler_proto_rawDescOnce.Do(func() {
		file_proto_lib_crawler_v1_crawler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_lib_crawler_v1_crawler_proto_rawDesc), len(file_proto_lib_crawler_v1_crawler_proto_rawDesc)))
	})
	return file_proto_lib_crawler_v1_crawler_proto_rawDescData
}

var file_proto_lib_crawler_v1_crawler_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_lib_crawler_v1_crawler_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_lib_crawler_v1_crawler_proto_goTypes = []any{
	(CrawlStatus)(0),              // 0: erg.ninja.lib.crawler.v1.CrawlStatus
	(FeedType)(0),                 // 1: erg.ninja.lib.crawler.v1.FeedType
	(Priority)(0),                 // 2: erg.ninja.lib.crawler.v1.Priority
	(*CrawlURLRequest)(nil),       // 3: erg.ninja.lib.crawler.v1.CrawlURLRequest
	(*CrawlURLResponse)(nil),      // 4: erg.ninja.lib.crawler.v1.CrawlURLResponse
	(*GetCrawlStatusRequest)(nil), // 5: erg.ninja.lib.crawler.v1.GetCrawlStatusRequest
	(*CrawlStatusResponse)(nil),   // 6: erg.ninja.lib.crawler.v1.CrawlStatusResponse
	(*ListFeedsRequest)(nil),      // 7: erg.ninja.lib.crawler.v1.ListFeedsRequest
	(*Feed)(nil),                  // 8: erg.ninja.lib.crawler.v1.Feed
	(*ListFeedsResponse)(nil),     // 9: erg.ninja.lib.crawler.v1.ListFeedsResponse
	(*RefreshFeedRequest)(nil),    // 10: erg.ninja.lib.crawler.v1.RefreshFeedRequest
	(*RefreshFeedResponse)(nil),   // 11: erg.ninja.lib.crawler.v1.RefreshFeedResponse
	(*GetStatsRequest)(nil),       // 12: erg.ninja.lib.crawler.v1.GetStatsRequest
	(*StatsResponse)(nil),         // 13: erg.ninja.lib.crawler.v1.StatsResponse
	(*StopCrawlRequest)(nil),      // 14: erg.ninja.lib.crawler.v1.StopCrawlRequest
	(*StopCrawlResponse)(nil),     // 15: erg.ninja.lib.crawler.v1.StopCrawlResponse
	(*CrawlHistoryRequest)(nil),   // 16: erg.ninja.lib.crawler.v1.CrawlHistoryRequest
	(*CrawlHistoryItem)(nil),      // 17: erg.ninja.lib.crawler.v1.CrawlHistoryItem
	(*CrawlHistoryResponse)(nil),  // 18: erg.ninja.lib.crawler.v1.CrawlHistoryResponse
	(*ReindexRequest)(nil),        // 19: erg.ninja.lib.crawler.v1.ReindexRequest
	(*ReindexResponse)(nil),       // 20: erg.ninja.lib.crawler.v1.ReindexResponse
	(*timestamppb.Timestamp)(nil), // 21: google.protobuf.Timestamp
}
var file_proto_lib_crawler_v1_crawler_proto_depIdxs = []int32{
	2,  // 0: erg.ninja.lib.crawler.v1.CrawlURLRequest.priority:type_name -> erg.ninja.lib.crawler.v1.Priority
	0,  // 1: erg.ninja.lib.crawler.v1.CrawlURLResponse.status:type_name -> erg.ninja.lib.crawler.v1.CrawlStatus
	21, // 2: erg.ninja.lib.crawler.v1.CrawlURLResponse.created_at:type_name -> google.protobuf.Timestamp
	0,  // 3: erg.ninja.lib.crawler.v1.CrawlStatusResponse.status:type_name -> erg.ninja.lib.crawler.v1.CrawlStatus
	21, // 4: erg.ninja.lib.crawler.v1.CrawlStatusResponse.crawled_at:type_name -> google.protobuf.Timestamp
	21, // 5: erg.ninja.lib.crawler.v1.CrawlStatusResponse.created_at:type_name -> google.protobuf.Timestamp
	1,  // 6: erg.ninja.lib.crawler.v1.Feed.feed_type:type_name -> erg.ninja.lib.crawler.v1.FeedType
	21, // 7: erg.ninja.lib.crawler.v1.Feed.last_fetch_at:type_name -> google.protobuf.Timestamp
	21, // 8: erg.ninja.lib.crawler.v1.Feed.last_item_at:type_name -> google.protobuf.Timestamp
	21, // 9: erg.ninja.lib.crawler.v1.Feed.created_at:type_name -> google.protobuf.Timestamp
	21, // 10: erg.ninja.lib.crawler.v1.Feed.updated_at:type_name -> google.protobuf.Timestamp
	8,  // 11: erg.ninja.lib.crawler.v1.ListFeedsResponse.feeds:type_name -> erg.ninja.lib.crawler.v1.Feed
	21, // 12: erg.ninja.lib.crawler.v1.RefreshFeedResponse.refreshed_at:type_name -> google.protobuf.Timestamp
	21, // 13: erg.ninja.lib.crawler.v1.StatsResponse.last_refresh_at:type_name -> google.protobuf.Timestamp
	0,  // 14: erg.ninja.lib.crawler.v1.CrawlHistoryRequest.status:type_name -> erg.ninja.lib.crawler.v1.CrawlStatus
	0,  // 15: erg.ninja.lib.crawler.v1.CrawlHistoryItem.status:type_name -> erg.ninja.lib.crawler.v1.CrawlStatus
	21, // 16: erg.ninja.lib.crawler.v1.CrawlHistoryItem.crawled_at:type_name -> google.protobuf.Timestamp
	17, // 17: erg.ninja.lib.crawler.v1.CrawlHistoryResponse.items:type_name -> erg.ninja.lib.crawler.v1.CrawlHistoryItem
	21, // 18: erg.ninja.lib.crawler.v1.ReindexResponse.started_at:type_name -> google.protobuf.Timestamp
	3,  // 19: erg.ninja.lib.crawler.v1.CrawlerService.CrawlURL:input_type -> erg.ninja.lib.crawler.v1.CrawlURLRequest
	5,  // 20: erg.ninja.lib.crawler.v1.CrawlerService.GetCrawlStatus:input_type -> erg.ninja.lib.crawler.v1.GetCrawlStatusRequest
	7,  // 21: erg.ninja.lib.crawler.v1.CrawlerService.ListFeeds:input_type -> erg.ninja.lib.crawler.v1.ListFeedsRequest
	10, // 22: erg.ninja.lib.crawler.v1.CrawlerService.RefreshFeed:input_type -> erg.ninja.lib.crawler.v1.RefreshFeedRequest
	12, // 23: erg.ninja.lib.crawler.v1.CrawlerService.GetStats:input_type -> erg.ninja.lib.crawler.v1.GetStatsRequest
	14, // 24: erg.ninja.lib.crawler.v1.CrawlerService.StopCrawl:input_type -> erg.ninja.lib.crawler.v1.StopCrawlRequest
	16, // 25: erg.ninja.lib.crawler.v1.CrawlerService.GetCrawlHistory:input_type -> erg.ninja.lib.crawler.v1.CrawlHistoryRequest
	19, // 26: erg.ninja.lib.crawler.v1.CrawlerService.Reindex:input_type -> erg.ninja.lib.crawler.v1.ReindexRequest
	4,  // 27: erg.ninja.lib.crawler.v1.CrawlerService.CrawlURL:output_type -> erg.ninja.lib.crawler.v1.CrawlURLResponse
	6,  // 28: erg.ninja.lib.crawler.v1.CrawlerService.GetCrawlStatus:output_type -> erg.ninja.lib.crawler.v1.CrawlStatusResponse
	9,  // 29: erg.ninja.lib.crawler.v1.CrawlerService.ListFeeds:output_type -> erg.ninja.lib.crawler.v1.ListFeedsResponse
	11, // 30: erg.ninja.lib.crawler.v1.CrawlerService.RefreshFeed:output_type -> erg.ninja.lib.crawler.v1.RefreshFeedResponse
	13, // 31: erg.ninja.lib.crawler.v1.CrawlerService.GetStats:output_type -> erg.ninja.lib.crawler.v1.StatsResponse
	15, // 32: erg.ninja.lib.crawler.v1.CrawlerService.StopCrawl:output_type -> erg.ninja.lib.crawler.v1.StopCrawlResponse
	18, // 33: erg.ninja.lib.crawler.v1.CrawlerService.GetCrawlHistory:output_type -> erg.ninja.lib.crawler.v1.CrawlHistoryResponse
	20, // 34: erg.ninja.lib.crawler.v1.CrawlerService.Reindex:output_type -> erg.ninja.lib.crawler.v1.ReindexResponse
	27, // [27:35] is the sub-list for method output_type
	19, // [19:27] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_proto_lib_crawler_v1_crawler_proto_init() }
func file_proto_lib_crawler_v1_crawler_proto_init() {
	if File_proto_lib_crawler_v1_crawler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_lib_crawler_v1_crawler_proto_rawDesc), len(file_proto_lib_crawler_v1_crawler_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_lib_crawler_v1_crawler_proto_goTypes,
		DependencyIndexes: file_proto_lib_crawler_v1_crawler_proto_depIdxs,
		EnumInfos:         file_proto_lib_crawler_v1_crawler_proto_enumTypes,
		MessageInfos:      file_proto_lib_crawler_v1_crawler_proto_msgTypes,
	}.Build()
	File_proto_lib_crawler_v1_crawler_proto = out.File
	file_proto_lib_crawler_v1_crawler_proto_goTypes = nil
	file_proto_lib_crawler_v1_crawler_proto_depIdxs = nil
}
