// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/lib/crawler/v1/crawler.proto

package crawlerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CrawlerService_CrawlURL_FullMethodName        = "/erg.ninja.lib.crawler.v1.CrawlerService/CrawlURL"
	CrawlerService_GetCrawlStatus_FullMethodName  = "/erg.ninja.lib.crawler.v1.CrawlerService/GetCrawlStatus"
	CrawlerService_ListFeeds_FullMethodName       = "/erg.ninja.lib.crawler.v1.CrawlerService/ListFeeds"
	CrawlerService_RefreshFeed_FullMethodName     = "/erg.ninja.lib.crawler.v1.CrawlerService/RefreshFeed"
	CrawlerService_GetStats_FullMethodName        = "/erg.ninja.lib.crawler.v1.CrawlerService/GetStats"
	CrawlerService_StopCrawl_FullMethodName       = "/erg.ninja.lib.crawler.v1.CrawlerService/StopCrawl"
	CrawlerService_GetCrawlHistory_FullMethodName = "/erg.ninja.lib.crawler.v1.CrawlerService/GetCrawlHistory"
	CrawlerService_Reindex_FullMethodName         = "/erg.ninja.lib.crawler.v1.CrawlerService/Reindex"
)

// CrawlerServiceClient is the client API for CrawlerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CrawlerServiceClient interface {
	// Submit a URL for crawling
	CrawlURL(ctx context.Context, in *CrawlURLRequest, opts ...grpc.CallOption) (*CrawlURLResponse, error)
	// Check the status of a crawl job
	GetCrawlStatus(ctx context.Context, in *GetCrawlStatusRequest, opts ...grpc.CallOption) (*CrawlStatusResponse, error)
	// List all monitored RSS/Atom/JSON feeds
	ListFeeds(ctx context.Context, in *ListFeedsRequest, opts ...grpc.CallOption) (*ListFeedsResponse, error)
	// Force-refresh a feed, enqueuing new items
	RefreshFeed(ctx context.Context, in *RefreshFeedRequest, opts ...grpc.CallOption) (*RefreshFeedResponse, error)
	// Get aggregate crawler statistics
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	// Cancel a running or pending crawl job
	StopCrawl(ctx context.Context, in *StopCrawlRequest, opts ...grpc.CallOption) (*StopCrawlResponse, error)
	// Get crawl history for a tenant
	GetCrawlHistory(ctx context.Context, in *CrawlHistoryRequest, opts ...grpc.CallOption) (*CrawlHistoryResponse, error)
	// Trigger reindexing of content fingerprints
	Reindex(ctx context.Context, in *ReindexRequest, opts ...grpc.CallOption) (*ReindexResponse, error)
}

type crawlerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCrawlerServiceClient(cc grpc.ClientConnInterface) CrawlerServiceClient {
	return &crawlerServiceClient{cc}
}

func (c *crawlerServiceClient) CrawlURL(ctx context.Context, in *CrawlURLRequest, opts ...grpc.CallOption) (*CrawlURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CrawlURLResponse)
	err := c.cc.Invoke(ctx, CrawlerService_CrawlURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crawlerServiceClient) GetCrawlStatus(ctx context.Context, in *GetCrawlStatusRequest, opts ...grpc.CallOption) (*CrawlStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CrawlStatusResponse)
	err := c.cc.Invoke(ctx, CrawlerService_GetCrawlStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crawlerServiceClient) ListFeeds(ctx context.Context, in *ListFeedsRequest, opts ...grpc.CallOption) (*ListFeedsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFeedsResponse)
	err := c.cc.Invoke(ctx, CrawlerService_ListFeeds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crawlerServiceClient) RefreshFeed(ctx context.Context, in *RefreshFeedRequest, opts ...grpc.CallOption) (*RefreshFeedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshFeedResponse)
	err := c.cc.Invoke(ctx, CrawlerService_RefreshFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crawlerServiceClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, CrawlerService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crawlerServiceClient) StopCrawl(ctx context.Context, in *StopCrawlRequest, opts ...grpc.CallOption) (*StopCrawlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopCrawlResponse)
	err := c.cc.Invoke(ctx, CrawlerService_StopCrawl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crawlerServiceClient) GetCrawlHistory(ctx context.Context, in *CrawlHistoryRequest, opts ...grpc.CallOption) (*CrawlHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CrawlHistoryResponse)
	err := c.cc.Invoke(ctx, CrawlerService_GetCrawlHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crawlerServiceClient) Reindex(ctx context.Context, in *ReindexRequest, opts ...grpc.CallOption) (*ReindexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReindexResponse)
	err := c.cc.Invoke(ctx, CrawlerService_Reindex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrawlerServiceServer is the server API for CrawlerService service.
// All implementations must embed UnimplementedCrawlerServiceServer
// for forward compatibility.
type CrawlerServiceServer interface {
	// Submit a URL for crawling
	CrawlURL(context.Context, *CrawlURLRequest) (*CrawlURLResponse, error)
	// Check the status of a crawl job
	GetCrawlStatus(context.Context, *GetCrawlStatusRequest) (*CrawlStatusResponse, error)
	// List all monitored RSS/Atom/JSON feeds
	ListFeeds(context.Context, *ListFeedsRequest) (*ListFeedsResponse, error)
	// Force-refresh a feed, enqueuing new items
	RefreshFeed(context.Context, *RefreshFeedRequest) (*RefreshFeedResponse, error)
	// Get aggregate crawler statistics
	GetStats(context.Context, *GetStatsRequest) (*StatsResponse, error)
	// Cancel a running or pending crawl job
	StopCrawl(context.Context, *StopCrawlRequest) (*StopCrawlResponse, error)
	// Get crawl history for a tenant
	GetCrawlHistory(context.Context, *CrawlHistoryRequest) (*CrawlHistoryResponse, error)
	// Trigger reindexing of content fingerprints
	Reindex(context.Context, *ReindexRequest) (*ReindexResponse, error)
	mustEmbedUnimplementedCrawlerServiceServer()
}

// UnimplementedCrawlerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCrawlerServiceServer struct{}

func (UnimplementedCrawlerServiceServer) CrawlURL(context.Context, *CrawlURLRequest) (*CrawlURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CrawlURL not implemented")
}
func (UnimplementedCrawlerServiceServer) GetCrawlStatus(context.Context, *GetCrawlStatusRequest) (*CrawlStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCrawlStatus not implemented")
}
func (UnimplementedCrawlerServiceServer) ListFeeds(context.Context, *ListFeedsRequest) (*ListFeedsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFeeds not implemented")
}
func (UnimplementedCrawlerServiceServer) RefreshFeed(context.Context, *RefreshFeedRequest) (*RefreshFeedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshFeed not implemented")
}
func (UnimplementedCrawlerServiceServer) GetStats(context.Context, *GetStatsRequest) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedCrawlerServiceServer) StopCrawl(context.Context, *StopCrawlRequest) (*StopCrawlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopCrawl not implemented")
}
func (UnimplementedCrawlerServiceServer) GetCrawlHistory(context.Context, *CrawlHistoryRequest) (*CrawlHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCrawlHistory not implemented")
}
func (UnimplementedCrawlerServiceServer) Reindex(context.Context, *ReindexRequest) (*ReindexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reindex not implemented")
}
func (UnimplementedCrawlerServiceServer) mustEmbedUnimplementedCrawlerServiceServer() {}
func (UnimplementedCrawlerServiceServer) testEmbeddedByValue()                        {}

// UnsafeCrawlerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CrawlerServiceServer will
// result in compilation errors.
type UnsafeCrawlerServiceServer interface {
	mustEmbedUnimplementedCrawlerServiceServer()
}

func RegisterCrawlerServiceServer(s grpc.ServiceRegistrar, srv CrawlerServiceServer) {
	// If the following call panics, it indicates UnimplementedCrawlerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CrawlerService_ServiceDesc, srv)
}

func _CrawlerService_CrawlURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrawlURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlerServiceServer).CrawlURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrawlerService_CrawlURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlerServiceServer).CrawlURL(ctx, req.(*CrawlURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrawlerService_GetCrawlStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCrawlStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlerServiceServer).GetCrawlStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrawlerService_GetCrawlStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlerServiceServer).GetCrawlStatus(ctx, req.(*GetCrawlStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrawlerService_ListFeeds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFeedsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlerServiceServer).ListFeeds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrawlerService_ListFeeds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlerServiceServer).ListFeeds(ctx, req.(*ListFeedsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrawlerService_RefreshFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlerServiceServer).RefreshFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrawlerService_RefreshFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlerServiceServer).RefreshFeed(ctx, req.(*RefreshFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrawlerService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlerServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrawlerService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlerServiceServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrawlerService_StopCrawl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopCrawlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlerServiceServer).StopCrawl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrawlerService_StopCrawl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlerServiceServer).StopCrawl(ctx, req.(*StopCrawlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrawlerService_GetCrawlHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrawlHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlerServiceServer).GetCrawlHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrawlerService_GetCrawlHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlerServiceServer).GetCrawlHistory(ctx, req.(*CrawlHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrawlerService_Reindex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReindexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlerServiceServer).Reindex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrawlerService_Reindex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlerServiceServer).Reindex(ctx, req.(*ReindexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CrawlerService_ServiceDesc is the grpc.ServiceDesc for CrawlerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CrawlerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "erg.ninja.lib.crawler.v1.CrawlerService",
	HandlerType: (*CrawlerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CrawlURL",
			Handler:    _CrawlerService_CrawlURL_Handler,
		},
		{
			MethodName: "GetCrawlStatus",
			Handler:    _CrawlerService_GetCrawlStatus_Handler,
		},
		{
			MethodName: "ListFeeds",
			Handler:    _CrawlerService_ListFeeds_Handler,
		},
		{
			MethodName: "RefreshFeed",
			Handler:    _CrawlerService_RefreshFeed_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _CrawlerService_GetStats_Handler,
		},
		{
			MethodName: "StopCrawl",
			Handler:    _CrawlerService_StopCrawl_Handler,
		},
		{
			MethodName: "GetCrawlHistory",
			Handler:    _CrawlerService_GetCrawlHistory_Handler,
		},
		{
			MethodName: "Reindex",
			Handler:    _CrawlerService_Reindex_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/lib/crawler/v1/crawler.proto",
}
